// Code generated by counterfeiter. DO NOT EDIT.
package states

import (
	"sync"
)

type FakeAgentStateMachine struct {
	CanTransitionStub        func(*AgentContext, AgentExecutionState) bool
	canTransitionMutex       sync.RWMutex
	canTransitionArgsForCall []struct {
		arg1 *AgentContext
		arg2 AgentExecutionState
	}
	canTransitionReturns struct {
		result1 bool
	}
	canTransitionReturnsOnCall map[int]struct {
		result1 bool
	}
	GetCurrentStateStub        func() AgentExecutionState
	getCurrentStateMutex       sync.RWMutex
	getCurrentStateArgsForCall []struct {
	}
	getCurrentStateReturns struct {
		result1 AgentExecutionState
	}
	getCurrentStateReturnsOnCall map[int]struct {
		result1 AgentExecutionState
	}
	GetPreviousStateStub        func() AgentExecutionState
	getPreviousStateMutex       sync.RWMutex
	getPreviousStateArgsForCall []struct {
	}
	getPreviousStateReturns struct {
		result1 AgentExecutionState
	}
	getPreviousStateReturnsOnCall map[int]struct {
		result1 AgentExecutionState
	}
	GetValidTransitionsStub        func(*AgentContext) []AgentExecutionState
	getValidTransitionsMutex       sync.RWMutex
	getValidTransitionsArgsForCall []struct {
		arg1 *AgentContext
	}
	getValidTransitionsReturns struct {
		result1 []AgentExecutionState
	}
	getValidTransitionsReturnsOnCall map[int]struct {
		result1 []AgentExecutionState
	}
	ResetStub        func()
	resetMutex       sync.RWMutex
	resetArgsForCall []struct {
	}
	TransitionStub        func(*AgentContext, AgentExecutionState) error
	transitionMutex       sync.RWMutex
	transitionArgsForCall []struct {
		arg1 *AgentContext
		arg2 AgentExecutionState
	}
	transitionReturns struct {
		result1 error
	}
	transitionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentStateMachine) CanTransition(arg1 *AgentContext, arg2 AgentExecutionState) bool {
	fake.canTransitionMutex.Lock()
	ret, specificReturn := fake.canTransitionReturnsOnCall[len(fake.canTransitionArgsForCall)]
	fake.canTransitionArgsForCall = append(fake.canTransitionArgsForCall, struct {
		arg1 *AgentContext
		arg2 AgentExecutionState
	}{arg1, arg2})
	stub := fake.CanTransitionStub
	fakeReturns := fake.canTransitionReturns
	fake.recordInvocation("CanTransition", []interface{}{arg1, arg2})
	fake.canTransitionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentStateMachine) CanTransitionCallCount() int {
	fake.canTransitionMutex.RLock()
	defer fake.canTransitionMutex.RUnlock()
	return len(fake.canTransitionArgsForCall)
}

func (fake *FakeAgentStateMachine) CanTransitionCalls(stub func(*AgentContext, AgentExecutionState) bool) {
	fake.canTransitionMutex.Lock()
	defer fake.canTransitionMutex.Unlock()
	fake.CanTransitionStub = stub
}

func (fake *FakeAgentStateMachine) CanTransitionArgsForCall(i int) (*AgentContext, AgentExecutionState) {
	fake.canTransitionMutex.RLock()
	defer fake.canTransitionMutex.RUnlock()
	argsForCall := fake.canTransitionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentStateMachine) CanTransitionReturns(result1 bool) {
	fake.canTransitionMutex.Lock()
	defer fake.canTransitionMutex.Unlock()
	fake.CanTransitionStub = nil
	fake.canTransitionReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeAgentStateMachine) CanTransitionReturnsOnCall(i int, result1 bool) {
	fake.canTransitionMutex.Lock()
	defer fake.canTransitionMutex.Unlock()
	fake.CanTransitionStub = nil
	if fake.canTransitionReturnsOnCall == nil {
		fake.canTransitionReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.canTransitionReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeAgentStateMachine) GetCurrentState() AgentExecutionState {
	fake.getCurrentStateMutex.Lock()
	ret, specificReturn := fake.getCurrentStateReturnsOnCall[len(fake.getCurrentStateArgsForCall)]
	fake.getCurrentStateArgsForCall = append(fake.getCurrentStateArgsForCall, struct {
	}{})
	stub := fake.GetCurrentStateStub
	fakeReturns := fake.getCurrentStateReturns
	fake.recordInvocation("GetCurrentState", []interface{}{})
	fake.getCurrentStateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentStateMachine) GetCurrentStateCallCount() int {
	fake.getCurrentStateMutex.RLock()
	defer fake.getCurrentStateMutex.RUnlock()
	return len(fake.getCurrentStateArgsForCall)
}

func (fake *FakeAgentStateMachine) GetCurrentStateCalls(stub func() AgentExecutionState) {
	fake.getCurrentStateMutex.Lock()
	defer fake.getCurrentStateMutex.Unlock()
	fake.GetCurrentStateStub = stub
}

func (fake *FakeAgentStateMachine) GetCurrentStateReturns(result1 AgentExecutionState) {
	fake.getCurrentStateMutex.Lock()
	defer fake.getCurrentStateMutex.Unlock()
	fake.GetCurrentStateStub = nil
	fake.getCurrentStateReturns = struct {
		result1 AgentExecutionState
	}{result1}
}

func (fake *FakeAgentStateMachine) GetCurrentStateReturnsOnCall(i int, result1 AgentExecutionState) {
	fake.getCurrentStateMutex.Lock()
	defer fake.getCurrentStateMutex.Unlock()
	fake.GetCurrentStateStub = nil
	if fake.getCurrentStateReturnsOnCall == nil {
		fake.getCurrentStateReturnsOnCall = make(map[int]struct {
			result1 AgentExecutionState
		})
	}
	fake.getCurrentStateReturnsOnCall[i] = struct {
		result1 AgentExecutionState
	}{result1}
}

func (fake *FakeAgentStateMachine) GetPreviousState() AgentExecutionState {
	fake.getPreviousStateMutex.Lock()
	ret, specificReturn := fake.getPreviousStateReturnsOnCall[len(fake.getPreviousStateArgsForCall)]
	fake.getPreviousStateArgsForCall = append(fake.getPreviousStateArgsForCall, struct {
	}{})
	stub := fake.GetPreviousStateStub
	fakeReturns := fake.getPreviousStateReturns
	fake.recordInvocation("GetPreviousState", []interface{}{})
	fake.getPreviousStateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentStateMachine) GetPreviousStateCallCount() int {
	fake.getPreviousStateMutex.RLock()
	defer fake.getPreviousStateMutex.RUnlock()
	return len(fake.getPreviousStateArgsForCall)
}

func (fake *FakeAgentStateMachine) GetPreviousStateCalls(stub func() AgentExecutionState) {
	fake.getPreviousStateMutex.Lock()
	defer fake.getPreviousStateMutex.Unlock()
	fake.GetPreviousStateStub = stub
}

func (fake *FakeAgentStateMachine) GetPreviousStateReturns(result1 AgentExecutionState) {
	fake.getPreviousStateMutex.Lock()
	defer fake.getPreviousStateMutex.Unlock()
	fake.GetPreviousStateStub = nil
	fake.getPreviousStateReturns = struct {
		result1 AgentExecutionState
	}{result1}
}

func (fake *FakeAgentStateMachine) GetPreviousStateReturnsOnCall(i int, result1 AgentExecutionState) {
	fake.getPreviousStateMutex.Lock()
	defer fake.getPreviousStateMutex.Unlock()
	fake.GetPreviousStateStub = nil
	if fake.getPreviousStateReturnsOnCall == nil {
		fake.getPreviousStateReturnsOnCall = make(map[int]struct {
			result1 AgentExecutionState
		})
	}
	fake.getPreviousStateReturnsOnCall[i] = struct {
		result1 AgentExecutionState
	}{result1}
}

func (fake *FakeAgentStateMachine) GetValidTransitions(arg1 *AgentContext) []AgentExecutionState {
	fake.getValidTransitionsMutex.Lock()
	ret, specificReturn := fake.getValidTransitionsReturnsOnCall[len(fake.getValidTransitionsArgsForCall)]
	fake.getValidTransitionsArgsForCall = append(fake.getValidTransitionsArgsForCall, struct {
		arg1 *AgentContext
	}{arg1})
	stub := fake.GetValidTransitionsStub
	fakeReturns := fake.getValidTransitionsReturns
	fake.recordInvocation("GetValidTransitions", []interface{}{arg1})
	fake.getValidTransitionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentStateMachine) GetValidTransitionsCallCount() int {
	fake.getValidTransitionsMutex.RLock()
	defer fake.getValidTransitionsMutex.RUnlock()
	return len(fake.getValidTransitionsArgsForCall)
}

func (fake *FakeAgentStateMachine) GetValidTransitionsCalls(stub func(*AgentContext) []AgentExecutionState) {
	fake.getValidTransitionsMutex.Lock()
	defer fake.getValidTransitionsMutex.Unlock()
	fake.GetValidTransitionsStub = stub
}

func (fake *FakeAgentStateMachine) GetValidTransitionsArgsForCall(i int) *AgentContext {
	fake.getValidTransitionsMutex.RLock()
	defer fake.getValidTransitionsMutex.RUnlock()
	argsForCall := fake.getValidTransitionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentStateMachine) GetValidTransitionsReturns(result1 []AgentExecutionState) {
	fake.getValidTransitionsMutex.Lock()
	defer fake.getValidTransitionsMutex.Unlock()
	fake.GetValidTransitionsStub = nil
	fake.getValidTransitionsReturns = struct {
		result1 []AgentExecutionState
	}{result1}
}

func (fake *FakeAgentStateMachine) GetValidTransitionsReturnsOnCall(i int, result1 []AgentExecutionState) {
	fake.getValidTransitionsMutex.Lock()
	defer fake.getValidTransitionsMutex.Unlock()
	fake.GetValidTransitionsStub = nil
	if fake.getValidTransitionsReturnsOnCall == nil {
		fake.getValidTransitionsReturnsOnCall = make(map[int]struct {
			result1 []AgentExecutionState
		})
	}
	fake.getValidTransitionsReturnsOnCall[i] = struct {
		result1 []AgentExecutionState
	}{result1}
}

func (fake *FakeAgentStateMachine) Reset() {
	fake.resetMutex.Lock()
	fake.resetArgsForCall = append(fake.resetArgsForCall, struct {
	}{})
	stub := fake.ResetStub
	fake.recordInvocation("Reset", []interface{}{})
	fake.resetMutex.Unlock()
	if stub != nil {
		fake.ResetStub()
	}
}

func (fake *FakeAgentStateMachine) ResetCallCount() int {
	fake.resetMutex.RLock()
	defer fake.resetMutex.RUnlock()
	return len(fake.resetArgsForCall)
}

func (fake *FakeAgentStateMachine) ResetCalls(stub func()) {
	fake.resetMutex.Lock()
	defer fake.resetMutex.Unlock()
	fake.ResetStub = stub
}

func (fake *FakeAgentStateMachine) Transition(arg1 *AgentContext, arg2 AgentExecutionState) error {
	fake.transitionMutex.Lock()
	ret, specificReturn := fake.transitionReturnsOnCall[len(fake.transitionArgsForCall)]
	fake.transitionArgsForCall = append(fake.transitionArgsForCall, struct {
		arg1 *AgentContext
		arg2 AgentExecutionState
	}{arg1, arg2})
	stub := fake.TransitionStub
	fakeReturns := fake.transitionReturns
	fake.recordInvocation("Transition", []interface{}{arg1, arg2})
	fake.transitionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentStateMachine) TransitionCallCount() int {
	fake.transitionMutex.RLock()
	defer fake.transitionMutex.RUnlock()
	return len(fake.transitionArgsForCall)
}

func (fake *FakeAgentStateMachine) TransitionCalls(stub func(*AgentContext, AgentExecutionState) error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = stub
}

func (fake *FakeAgentStateMachine) TransitionArgsForCall(i int) (*AgentContext, AgentExecutionState) {
	fake.transitionMutex.RLock()
	defer fake.transitionMutex.RUnlock()
	argsForCall := fake.transitionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentStateMachine) TransitionReturns(result1 error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = nil
	fake.transitionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentStateMachine) TransitionReturnsOnCall(i int, result1 error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = nil
	if fake.transitionReturnsOnCall == nil {
		fake.transitionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.transitionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentStateMachine) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentStateMachine) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ AgentStateMachine = new(FakeAgentStateMachine)
