package setup

import (
	"fmt"
	"strings"
)

// InstallSkill is the catalog skill carrying the infer-action workflow
// authoring guide and its bundled examples. Mentioning it as "/<name>" in the
// agent prompt activates it (downloaded from the skills catalog on demand).
const InstallSkill = "github-workflow"

// installPromptParams feeds installPrompt; every field is plain data so the
// builder is trivially unit-testable.
type installPromptParams struct {
	Dir       string   // absolute path of the shallow checkout
	Repo      string   // owner/name
	Languages string   // comma-separated, from the GitHub languages API ("" when unknown)
	Existing  []string // repo-relative workflow files already using infer-action
	CIPath    string   // repo-relative CI workflow to take inspiration from ("" when none)
	GitHubApp bool     // prefer the GitHub App token variant
	Context   string   // extra user-supplied instructions
}

// installPrompt builds the task for the headless agent that creates or updates
// the infer-action workflow inside the checkout.
func installPrompt(p installPromptParams) string {
	var b strings.Builder
	fmt.Fprintf(&b, `/%s

Update the GitHub Actions workflow for the OpenTask agent (inference-gateway/infer-action) in the repository %s.

A shallow checkout is at %s - work ONLY inside that directory, using the Read/Grep/Tree/Write/Edit tools with absolute paths. Do NOT run git and do NOT create commits, branches, or pull requests; the caller handles all of that.

Read the /%s skill's guide and its bundled example workflows FIRST - they are the canonical infer-action usage patterns. Then read the existing workflow in the checkout, and only then make your changes.

`, InstallSkill, p.Repo, p.Dir, InstallSkill)

	if len(p.Existing) > 0 {
		fmt.Fprintf(&b, `The workflow already exists: %s. Apply ONLY infer-action-related changes:
- Bump the inference-gateway/infer-action version to the latest release.
- Add any workflow_dispatch inputs and infer-action "with:" attributes from the skill's canonical workflow that are missing.
- NEVER remove or rewrite repo-specific content: GitHub App token steps, checkout tokens, setup/build steps, languages/apt settings, plugins, agents, extra bash-allow-append entries, custom instructions, or any other local customization. When in doubt, keep what is there.
`, strings.Join(p.Existing, ", "))
	} else {
		b.WriteString(`No infer-action workflow exists yet. Create .github/workflows/tasks.yml following the skill's canonical workflow, tailored to this repository. Do not add any comments to the file - it must be clean YAML.
`)
	}

	if p.Languages != "" {
		fmt.Fprintf(&b, "\nThe repository's languages (per GitHub) are: %s. Keep or add matching languages/setup steps so the agent can build and test the project.\n", p.Languages)
	}
	if p.CIPath != "" {
		fmt.Fprintf(&b, "\nRead %s and take inspiration from its conventions: setup steps, action choices and versions, token/GitHub App usage.\n", p.CIPath)
	}
	if p.GitHubApp {
		b.WriteString("\nUse the GitHub App token variant: an actions/create-github-app-token step whose token feeds checkout and the infer-action github-token input.\n")
	}

	b.WriteString(`
Rules:
- Explore the project as needed to make the workflow fit it.
- Every GitHub Action must be pinned to its latest release using the explicit v<major>.<minor>.<patch> form (e.g. actions/checkout@v7.0.1), never a floating major like @v4.
- No "generated by" or AI-attribution footers anywhere.
`)

	if strings.TrimSpace(p.Context) != "" {
		fmt.Fprintf(&b, "\nAdditional context from the user:\n%s\n", strings.TrimSpace(p.Context))
	}

	b.WriteString(`
When the workflow file is written, reply with ONLY a JSON object:
{"title": "<Conventional Commit PR title, e.g. ci: bump infer-action to the latest version>", "body": "<markdown PR body describing exactly what changed in the workflow and why>"}`)
	return b.String()
}
