repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '^\.flox/env/manifest\.lock$'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: local
    hooks:
      - id: mod-tidy
        name: Go mod tidy
        entry: flox activate -- task mod:tidy
        language: system
        files: '(go\.mod|go\.sum)$'
        pass_filenames: false
      - id: lint
        name: Lint
        entry: flox activate -- task lint
        language: system
        pass_filenames: false
