---
branches:
  - name: main
  - name: rc/*
    prerelease: rc
  - name: feat/*
    prerelease: feat-rc
  - name: feature/*
    prerelease: feature-rc
  - name: fix/*
    prerelease: fix-rc
  - name: refactor/*
    prerelease: refactor-rc

tagFormat: "v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: docs
          release: patch
        - type: style
          release: patch
        - type: refactor
          release: patch
        - type: test
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: revert
          release: patch
        - breaking: true
          release: minor

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "🚀 Features"
            hidden: false
          - type: fix
            section: "🐛 Bug Fixes"
            hidden: false
          - type: perf
            section: "⚡ Performance Improvements"
            hidden: false
          - type: refactor
            section: "♻️ Code Refactoring"
            hidden: false
          - type: docs
            section: "📚 Documentation"
            hidden: false
          - type: style
            section: "💄 Styles"
            hidden: false
          - type: test
            section: "✅ Tests"
            hidden: false
          - type: build
            section: "🔧 Build System"
            hidden: false
          - type: ci
            section: "👷 CI/CD"
            hidden: false
          - type: chore
            section: "🧹 Maintenance"
            hidden: false
          - type: revert
            section: "⏪ Reverts"
            hidden: false
      writerOpts:
        commitsSort:
          - subject
          - scope

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: |
        # Changelog

        All notable changes to this project will be documented in this file.

        The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
        and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}

  - - "@semantic-release/github"
    - releaseNameTemplate: "🚀 Version <%= nextRelease.version %>"
      releaseBodyTemplate: |
        ## What's Changed

        <%= nextRelease.notes %>

        ## 📦 Installation

        ### Quick Install (Recommended)

        Install the latest version using our install script:

        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/cli/main/install.sh | bash
        ```

        Or install a specific version:

        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/cli/main/install.sh | bash -s -- --version <%= nextRelease.gitTag %>
        ```

        Custom installation directory:

        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/cli/main/install.sh | bash -s -- --install-dir $HOME/.local/bin
        ```

        ### Binary Download

        Download the appropriate binary for your platform from the assets below.

        ### Container Image

        ```bash
        docker run --rm -it ghcr.io/inference-gateway/cli:<%= nextRelease.version %>
        ```

        ---

        **Full Changelog**: https://github.com/<%= env.GITHUB_REPOSITORY %>/compare/<%= lastRelease.gitTag %>...<%= nextRelease.gitTag %>
      discussionCategoryName: false
      addReleases: bottom
      releasedLabels:
        - "<%= nextRelease.channel ? 'prerelease' : 'released' %>"
