version: '3'

vars:
  BINARY_NAME: infer
  MAIN_PACKAGE: .
  VERSION:
    sh: echo "${VERSION:-$(git describe --tags --always --dirty 2>/dev/null || echo "dev")}"
  COMMIT:
    sh: echo "${COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}"
  DATE:
    sh: echo "${DATE:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the CLI binary
    cmds:
      - go build -ldflags "-X github.com/inference-gateway/cli/cmd.version={{.VERSION}} -X github.com/inference-gateway/cli/cmd.commit={{.COMMIT}} -X github.com/inference-gateway/cli/cmd.date={{.DATE}}" -o {{.BINARY_NAME}} {{.MAIN_PACKAGE}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_NAME}}"

  install:
    desc: Install the CLI from source
    cmds:
      - go build -ldflags "-X github.com/inference-gateway/cli/cmd.version={{.VERSION}} -X github.com/inference-gateway/cli/cmd.commit={{.COMMIT}} -X github.com/inference-gateway/cli/cmd.date={{.DATE}}" -o $(go env GOPATH)/bin/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - go clean

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -cover ./...

  lint:
    desc: Run linter (requires golangci-lint)
    cmds:
      - golangci-lint run
      - markdownlint . --ignore CHANGELOG.md --fix

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  mod:tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  mod:download:
    desc: Download go modules
    cmds:
      - go mod download

  run:
    desc: Run the CLI locally
    cmds:
      - go run {{.MAIN_PACKAGE}} {{.CLI_ARGS}}

  run:status:
    desc: Run status command locally
    cmds:
      - go run {{.MAIN_PACKAGE}} status

  run:version:
    desc: Run version command locally
    cmds:
      - go run {{.MAIN_PACKAGE}} version

  run:help:
    desc: Show CLI help
    cmds:
      - go run {{.MAIN_PACKAGE}} --help

  check:
    desc: Run all quality checks
    deps:
      - fmt
      - vet
      - lint
      - test

  dev:
    desc: Development workflow - format, build, and test
    deps:
      - fmt
      - build
      - test

  release:build:
    desc: Build release binaries for multiple platforms (Linux only - macOS builds require native runners)
    cmds:
      - mkdir -p dist
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/inference-gateway/cli/cmd.version={{.VERSION}} -X github.com/inference-gateway/cli/cmd.commit={{.COMMIT}} -X github.com/inference-gateway/cli/cmd.date={{.DATE}}" -o dist/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PACKAGE}}
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X github.com/inference-gateway/cli/cmd.version={{.VERSION}} -X github.com/inference-gateway/cli/cmd.commit={{.COMMIT}} -X github.com/inference-gateway/cli/cmd.date={{.DATE}}" -o dist/{{.BINARY_NAME}}-linux-arm64 {{.MAIN_PACKAGE}}
      - cd dist && sha256sum {{.BINARY_NAME}}-* > checksums.txt
      - cd dist && cosign sign-blob --yes --output-signature checksums.txt.sig --output-certificate checksums.txt.pem checksums.txt

  release:build:darwin:
    desc: Build macOS binary with CGO enabled (for clipboard image support)
    vars:
      GOARCH:
        sh: go env GOARCH
    cmds:
      - mkdir -p dist
      - CGO_ENABLED=1 GOOS=darwin GOARCH={{.GOARCH}} go build -ldflags "-X github.com/inference-gateway/cli/cmd.version={{.VERSION}} -X github.com/inference-gateway/cli/cmd.commit={{.COMMIT}} -X github.com/inference-gateway/cli/cmd.date={{.DATE}}" -o dist/{{.BINARY_NAME}}-darwin-{{.GOARCH}} {{.MAIN_PACKAGE}}

  container:push:
    desc: Push pre-built container images to registry
    vars:
      PUSH_LATEST:
        sh: echo "${PUSH_LATEST:-true}"
      LATEST_TAG:
        sh: |
          if [ "{{.PUSH_LATEST}}" = "true" ]; then
            echo "-t ghcr.io/inference-gateway/cli:latest"
          else
            echo ""
          fi
    cmds:
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t ghcr.io/inference-gateway/cli:{{.VERSION}} \
          {{.LATEST_TAG}} \
          --build-context binaries=dist/ \
          --build-arg VERSION={{.VERSION}} \
          --build-arg REVISION={{.COMMIT}} \
          --build-arg BUILD_DATE={{.DATE}} \
          --annotation "index:org.opencontainers.image.title=Inference Gateway CLI" \
          --annotation "index:org.opencontainers.image.description=A powerful command-line interface for managing and interacting with the Inference Gateway. Provides interactive chat, autonomous agent capabilities, and extensive tool execution for AI models." \
          --annotation "index:org.opencontainers.image.vendor=Inference Gateway" \
          --annotation "index:org.opencontainers.image.authors=Inference Gateway Team" \
          --annotation "index:org.opencontainers.image.url=https://github.com/inference-gateway/cli" \
          --annotation "index:org.opencontainers.image.documentation=https://github.com/inference-gateway/cli#readme" \
          --annotation "index:org.opencontainers.image.source=https://github.com/inference-gateway/cli" \
          --annotation "index:org.opencontainers.image.licenses=MIT" \
          --annotation "index:org.opencontainers.image.version={{.VERSION}}" \
          --annotation "index:org.opencontainers.image.revision={{.COMMIT}}" \
          --annotation "index:org.opencontainers.image.created={{.DATE}}" \
          -f Dockerfile \
          .

  deps:install:
    desc: Install development dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  setup:
    desc: Set up development environment
    deps:
      - deps:install
      - mod:download
      - precommit:install

  precommit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install

  precommit:run:
    desc: Run pre-commit on all files
    cmds:
      - pre-commit run --all-files

  mocks:generate:
    desc: Generate mocks using counterfeiter
    cmds:
      - mkdir -p tests/mocks/domain
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain Tool
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ToolFactory
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ToolService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain FileService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ImageService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain WebSearchService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain WebFetchService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain AgentService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ModelService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ConfigService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ThemeService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain ConversationRepository
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain SDKClient
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain StateManager
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain TaskTracker
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain A2AAgentService
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/domain MCPClient
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/domain internal/infra/storage ConversationStorage
      - mkdir -p tests/mocks/services
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/services internal/services TitleGenerator
      - mkdir -p tests/mocks/shortcuts
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/shortcuts internal/shortcuts Shortcut
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/shortcuts internal/shortcuts PersistentConversationRepository
      - mkdir -p tests/mocks/ui
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui ConversationRenderer
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui InputComponent
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui StatusComponent
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui HelpBarComponent
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui SelectionComponent
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui Theme
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui/autocomplete ShortcutRegistry
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/ui internal/ui AutocompleteComponent
      - mkdir -p tests/mocks/history
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/history internal/ui/history ShellHistoryProvider
      - mkdir -p tests/mocks/keybinding
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o tests/mocks/keybinding internal/ui/keybinding KeyHandlerContext
    sources:
      - "internal/domain/interfaces.go"
      - "internal/domain/agent.go"
      - "internal/domain/config_service.go"
      - "internal/infra/storage/interfaces.go"
      - "internal/ui/interfaces.go"
      - "internal/services/background_jobs.go"
      - "internal/shortcuts/interfaces.go"
    generates:
      - "tests/mocks/domain/fake_tool.go"
      - "tests/mocks/domain/fake_tool_factory.go"
      - "tests/mocks/domain/fake_tool_service.go"
      - "tests/mocks/domain/fake_web_search_service.go"
      - "tests/mocks/domain/fake_web_fetch_service.go"
      - "tests/mocks/domain/fake_file_service.go"
      - "tests/mocks/domain/fake_agent_service.go"
      - "tests/mocks/domain/fake_model_service.go"
      - "tests/mocks/domain/fake_config_service.go"
      - "tests/mocks/domain/fake_theme_service.go"
      - "tests/mocks/domain/fake_conversation_repository.go"
      - "tests/mocks/domain/fake_conversation_storage.go"
      - "tests/mocks/domain/fake_sdkclient.go"
      - "tests/mocks/domain/fake_task_tracker.go"
      - "tests/mocks/ui/fake_conversation_renderer.go"
      - "tests/mocks/ui/fake_input_component.go"
      - "tests/mocks/ui/fake_status_component.go"
      - "tests/mocks/ui/fake_help_bar_component.go"
      - "tests/mocks/ui/fake_selection_component.go"
      - "tests/mocks/ui/fake_theme.go"
      - "tests/mocks/ui/fake_autocomplete_interface.go"

  mocks:clean:
    desc: Clean generated mock files
    cmds:
      - rm -rf tests/mocks

  clean:release:
    desc: Clean release artifacts
    cmds:
      - rm -rf dist/
