// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeHistoryCleaner struct {
	ClearHistoryStub        func(context.Context, string) error
	clearHistoryMutex       sync.RWMutex
	clearHistoryArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	clearHistoryReturns struct {
		result1 error
	}
	clearHistoryReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHistoryCleaner) ClearHistory(arg1 context.Context, arg2 string) error {
	fake.clearHistoryMutex.Lock()
	ret, specificReturn := fake.clearHistoryReturnsOnCall[len(fake.clearHistoryArgsForCall)]
	fake.clearHistoryArgsForCall = append(fake.clearHistoryArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ClearHistoryStub
	fakeReturns := fake.clearHistoryReturns
	fake.recordInvocation("ClearHistory", []interface{}{arg1, arg2})
	fake.clearHistoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHistoryCleaner) ClearHistoryCallCount() int {
	fake.clearHistoryMutex.RLock()
	defer fake.clearHistoryMutex.RUnlock()
	return len(fake.clearHistoryArgsForCall)
}

func (fake *FakeHistoryCleaner) ClearHistoryCalls(stub func(context.Context, string) error) {
	fake.clearHistoryMutex.Lock()
	defer fake.clearHistoryMutex.Unlock()
	fake.ClearHistoryStub = stub
}

func (fake *FakeHistoryCleaner) ClearHistoryArgsForCall(i int) (context.Context, string) {
	fake.clearHistoryMutex.RLock()
	defer fake.clearHistoryMutex.RUnlock()
	argsForCall := fake.clearHistoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeHistoryCleaner) ClearHistoryReturns(result1 error) {
	fake.clearHistoryMutex.Lock()
	defer fake.clearHistoryMutex.Unlock()
	fake.ClearHistoryStub = nil
	fake.clearHistoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeHistoryCleaner) ClearHistoryReturnsOnCall(i int, result1 error) {
	fake.clearHistoryMutex.Lock()
	defer fake.clearHistoryMutex.Unlock()
	fake.ClearHistoryStub = nil
	if fake.clearHistoryReturnsOnCall == nil {
		fake.clearHistoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.clearHistoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeHistoryCleaner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHistoryCleaner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.HistoryCleaner = new(FakeHistoryCleaner)
