// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeMCPClient struct {
	CallToolStub        func(context.Context, string, string, map[string]any) (any, error)
	callToolMutex       sync.RWMutex
	callToolArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 map[string]any
	}
	callToolReturns struct {
		result1 any
		result2 error
	}
	callToolReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	DiscoverToolsStub        func(context.Context) (map[string][]domain.MCPDiscoveredTool, error)
	discoverToolsMutex       sync.RWMutex
	discoverToolsArgsForCall []struct {
		arg1 context.Context
	}
	discoverToolsReturns struct {
		result1 map[string][]domain.MCPDiscoveredTool
		result2 error
	}
	discoverToolsReturnsOnCall map[int]struct {
		result1 map[string][]domain.MCPDiscoveredTool
		result2 error
	}
	GetMCPServerStatusStub        func() *domain.MCPServerStatus
	getMCPServerStatusMutex       sync.RWMutex
	getMCPServerStatusArgsForCall []struct {
	}
	getMCPServerStatusReturns struct {
		result1 *domain.MCPServerStatus
	}
	getMCPServerStatusReturnsOnCall map[int]struct {
		result1 *domain.MCPServerStatus
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMCPClient) CallTool(arg1 context.Context, arg2 string, arg3 string, arg4 map[string]any) (any, error) {
	fake.callToolMutex.Lock()
	ret, specificReturn := fake.callToolReturnsOnCall[len(fake.callToolArgsForCall)]
	fake.callToolArgsForCall = append(fake.callToolArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 map[string]any
	}{arg1, arg2, arg3, arg4})
	stub := fake.CallToolStub
	fakeReturns := fake.callToolReturns
	fake.recordInvocation("CallTool", []interface{}{arg1, arg2, arg3, arg4})
	fake.callToolMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMCPClient) CallToolCallCount() int {
	fake.callToolMutex.RLock()
	defer fake.callToolMutex.RUnlock()
	return len(fake.callToolArgsForCall)
}

func (fake *FakeMCPClient) CallToolCalls(stub func(context.Context, string, string, map[string]any) (any, error)) {
	fake.callToolMutex.Lock()
	defer fake.callToolMutex.Unlock()
	fake.CallToolStub = stub
}

func (fake *FakeMCPClient) CallToolArgsForCall(i int) (context.Context, string, string, map[string]any) {
	fake.callToolMutex.RLock()
	defer fake.callToolMutex.RUnlock()
	argsForCall := fake.callToolArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMCPClient) CallToolReturns(result1 any, result2 error) {
	fake.callToolMutex.Lock()
	defer fake.callToolMutex.Unlock()
	fake.CallToolStub = nil
	fake.callToolReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPClient) CallToolReturnsOnCall(i int, result1 any, result2 error) {
	fake.callToolMutex.Lock()
	defer fake.callToolMutex.Unlock()
	fake.CallToolStub = nil
	if fake.callToolReturnsOnCall == nil {
		fake.callToolReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.callToolReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPClient) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMCPClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeMCPClient) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeMCPClient) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMCPClient) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMCPClient) DiscoverTools(arg1 context.Context) (map[string][]domain.MCPDiscoveredTool, error) {
	fake.discoverToolsMutex.Lock()
	ret, specificReturn := fake.discoverToolsReturnsOnCall[len(fake.discoverToolsArgsForCall)]
	fake.discoverToolsArgsForCall = append(fake.discoverToolsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DiscoverToolsStub
	fakeReturns := fake.discoverToolsReturns
	fake.recordInvocation("DiscoverTools", []interface{}{arg1})
	fake.discoverToolsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMCPClient) DiscoverToolsCallCount() int {
	fake.discoverToolsMutex.RLock()
	defer fake.discoverToolsMutex.RUnlock()
	return len(fake.discoverToolsArgsForCall)
}

func (fake *FakeMCPClient) DiscoverToolsCalls(stub func(context.Context) (map[string][]domain.MCPDiscoveredTool, error)) {
	fake.discoverToolsMutex.Lock()
	defer fake.discoverToolsMutex.Unlock()
	fake.DiscoverToolsStub = stub
}

func (fake *FakeMCPClient) DiscoverToolsArgsForCall(i int) context.Context {
	fake.discoverToolsMutex.RLock()
	defer fake.discoverToolsMutex.RUnlock()
	argsForCall := fake.discoverToolsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMCPClient) DiscoverToolsReturns(result1 map[string][]domain.MCPDiscoveredTool, result2 error) {
	fake.discoverToolsMutex.Lock()
	defer fake.discoverToolsMutex.Unlock()
	fake.DiscoverToolsStub = nil
	fake.discoverToolsReturns = struct {
		result1 map[string][]domain.MCPDiscoveredTool
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPClient) DiscoverToolsReturnsOnCall(i int, result1 map[string][]domain.MCPDiscoveredTool, result2 error) {
	fake.discoverToolsMutex.Lock()
	defer fake.discoverToolsMutex.Unlock()
	fake.DiscoverToolsStub = nil
	if fake.discoverToolsReturnsOnCall == nil {
		fake.discoverToolsReturnsOnCall = make(map[int]struct {
			result1 map[string][]domain.MCPDiscoveredTool
			result2 error
		})
	}
	fake.discoverToolsReturnsOnCall[i] = struct {
		result1 map[string][]domain.MCPDiscoveredTool
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPClient) GetMCPServerStatus() *domain.MCPServerStatus {
	fake.getMCPServerStatusMutex.Lock()
	ret, specificReturn := fake.getMCPServerStatusReturnsOnCall[len(fake.getMCPServerStatusArgsForCall)]
	fake.getMCPServerStatusArgsForCall = append(fake.getMCPServerStatusArgsForCall, struct {
	}{})
	stub := fake.GetMCPServerStatusStub
	fakeReturns := fake.getMCPServerStatusReturns
	fake.recordInvocation("GetMCPServerStatus", []interface{}{})
	fake.getMCPServerStatusMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMCPClient) GetMCPServerStatusCallCount() int {
	fake.getMCPServerStatusMutex.RLock()
	defer fake.getMCPServerStatusMutex.RUnlock()
	return len(fake.getMCPServerStatusArgsForCall)
}

func (fake *FakeMCPClient) GetMCPServerStatusCalls(stub func() *domain.MCPServerStatus) {
	fake.getMCPServerStatusMutex.Lock()
	defer fake.getMCPServerStatusMutex.Unlock()
	fake.GetMCPServerStatusStub = stub
}

func (fake *FakeMCPClient) GetMCPServerStatusReturns(result1 *domain.MCPServerStatus) {
	fake.getMCPServerStatusMutex.Lock()
	defer fake.getMCPServerStatusMutex.Unlock()
	fake.GetMCPServerStatusStub = nil
	fake.getMCPServerStatusReturns = struct {
		result1 *domain.MCPServerStatus
	}{result1}
}

func (fake *FakeMCPClient) GetMCPServerStatusReturnsOnCall(i int, result1 *domain.MCPServerStatus) {
	fake.getMCPServerStatusMutex.Lock()
	defer fake.getMCPServerStatusMutex.Unlock()
	fake.GetMCPServerStatusStub = nil
	if fake.getMCPServerStatusReturnsOnCall == nil {
		fake.getMCPServerStatusReturnsOnCall = make(map[int]struct {
			result1 *domain.MCPServerStatus
		})
	}
	fake.getMCPServerStatusReturnsOnCall[i] = struct {
		result1 *domain.MCPServerStatus
	}{result1}
}

func (fake *FakeMCPClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMCPClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.MCPClient = new(FakeMCPClient)
