// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeJobSubmitter struct {
	SubmitStub        func(domain.BackgroundJob)
	submitMutex       sync.RWMutex
	submitArgsForCall []struct {
		arg1 domain.BackgroundJob
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobSubmitter) Submit(arg1 domain.BackgroundJob) {
	fake.submitMutex.Lock()
	fake.submitArgsForCall = append(fake.submitArgsForCall, struct {
		arg1 domain.BackgroundJob
	}{arg1})
	stub := fake.SubmitStub
	fake.recordInvocation("Submit", []interface{}{arg1})
	fake.submitMutex.Unlock()
	if stub != nil {
		fake.SubmitStub(arg1)
	}
}

func (fake *FakeJobSubmitter) SubmitCallCount() int {
	fake.submitMutex.RLock()
	defer fake.submitMutex.RUnlock()
	return len(fake.submitArgsForCall)
}

func (fake *FakeJobSubmitter) SubmitCalls(stub func(domain.BackgroundJob)) {
	fake.submitMutex.Lock()
	defer fake.submitMutex.Unlock()
	fake.SubmitStub = stub
}

func (fake *FakeJobSubmitter) SubmitArgsForCall(i int) domain.BackgroundJob {
	fake.submitMutex.RLock()
	defer fake.submitMutex.RUnlock()
	argsForCall := fake.submitArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobSubmitter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobSubmitter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.JobSubmitter = new(FakeJobSubmitter)
