// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeJobStopper struct {
	WindJobStub        func(string, domain.WindSignal) error
	windJobMutex       sync.RWMutex
	windJobArgsForCall []struct {
		arg1 string
		arg2 domain.WindSignal
	}
	windJobReturns struct {
		result1 error
	}
	windJobReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobStopper) WindJob(arg1 string, arg2 domain.WindSignal) error {
	fake.windJobMutex.Lock()
	ret, specificReturn := fake.windJobReturnsOnCall[len(fake.windJobArgsForCall)]
	fake.windJobArgsForCall = append(fake.windJobArgsForCall, struct {
		arg1 string
		arg2 domain.WindSignal
	}{arg1, arg2})
	stub := fake.WindJobStub
	fakeReturns := fake.windJobReturns
	fake.recordInvocation("WindJob", []interface{}{arg1, arg2})
	fake.windJobMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobStopper) WindJobCallCount() int {
	fake.windJobMutex.RLock()
	defer fake.windJobMutex.RUnlock()
	return len(fake.windJobArgsForCall)
}

func (fake *FakeJobStopper) WindJobCalls(stub func(string, domain.WindSignal) error) {
	fake.windJobMutex.Lock()
	defer fake.windJobMutex.Unlock()
	fake.WindJobStub = stub
}

func (fake *FakeJobStopper) WindJobArgsForCall(i int) (string, domain.WindSignal) {
	fake.windJobMutex.RLock()
	defer fake.windJobMutex.RUnlock()
	argsForCall := fake.windJobArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobStopper) WindJobReturns(result1 error) {
	fake.windJobMutex.Lock()
	defer fake.windJobMutex.Unlock()
	fake.WindJobStub = nil
	fake.windJobReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStopper) WindJobReturnsOnCall(i int, result1 error) {
	fake.windJobMutex.Lock()
	defer fake.windJobMutex.Unlock()
	fake.WindJobStub = nil
	if fake.windJobReturnsOnCall == nil {
		fake.windJobReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.windJobReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobStopper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobStopper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.JobStopper = new(FakeJobStopper)
