// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeMemoryBackend struct {
	SyncInStub        func(context.Context) error
	syncInMutex       sync.RWMutex
	syncInArgsForCall []struct {
		arg1 context.Context
	}
	syncInReturns struct {
		result1 error
	}
	syncInReturnsOnCall map[int]struct {
		result1 error
	}
	SyncOutStub        func(context.Context) error
	syncOutMutex       sync.RWMutex
	syncOutArgsForCall []struct {
		arg1 context.Context
	}
	syncOutReturns struct {
		result1 error
	}
	syncOutReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMemoryBackend) SyncIn(arg1 context.Context) error {
	fake.syncInMutex.Lock()
	ret, specificReturn := fake.syncInReturnsOnCall[len(fake.syncInArgsForCall)]
	fake.syncInArgsForCall = append(fake.syncInArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SyncInStub
	fakeReturns := fake.syncInReturns
	fake.recordInvocation("SyncIn", []interface{}{arg1})
	fake.syncInMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMemoryBackend) SyncInCallCount() int {
	fake.syncInMutex.RLock()
	defer fake.syncInMutex.RUnlock()
	return len(fake.syncInArgsForCall)
}

func (fake *FakeMemoryBackend) SyncInCalls(stub func(context.Context) error) {
	fake.syncInMutex.Lock()
	defer fake.syncInMutex.Unlock()
	fake.SyncInStub = stub
}

func (fake *FakeMemoryBackend) SyncInArgsForCall(i int) context.Context {
	fake.syncInMutex.RLock()
	defer fake.syncInMutex.RUnlock()
	argsForCall := fake.syncInArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMemoryBackend) SyncInReturns(result1 error) {
	fake.syncInMutex.Lock()
	defer fake.syncInMutex.Unlock()
	fake.SyncInStub = nil
	fake.syncInReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMemoryBackend) SyncInReturnsOnCall(i int, result1 error) {
	fake.syncInMutex.Lock()
	defer fake.syncInMutex.Unlock()
	fake.SyncInStub = nil
	if fake.syncInReturnsOnCall == nil {
		fake.syncInReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.syncInReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMemoryBackend) SyncOut(arg1 context.Context) error {
	fake.syncOutMutex.Lock()
	ret, specificReturn := fake.syncOutReturnsOnCall[len(fake.syncOutArgsForCall)]
	fake.syncOutArgsForCall = append(fake.syncOutArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SyncOutStub
	fakeReturns := fake.syncOutReturns
	fake.recordInvocation("SyncOut", []interface{}{arg1})
	fake.syncOutMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMemoryBackend) SyncOutCallCount() int {
	fake.syncOutMutex.RLock()
	defer fake.syncOutMutex.RUnlock()
	return len(fake.syncOutArgsForCall)
}

func (fake *FakeMemoryBackend) SyncOutCalls(stub func(context.Context) error) {
	fake.syncOutMutex.Lock()
	defer fake.syncOutMutex.Unlock()
	fake.SyncOutStub = stub
}

func (fake *FakeMemoryBackend) SyncOutArgsForCall(i int) context.Context {
	fake.syncOutMutex.RLock()
	defer fake.syncOutMutex.RUnlock()
	argsForCall := fake.syncOutArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMemoryBackend) SyncOutReturns(result1 error) {
	fake.syncOutMutex.Lock()
	defer fake.syncOutMutex.Unlock()
	fake.SyncOutStub = nil
	fake.syncOutReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMemoryBackend) SyncOutReturnsOnCall(i int, result1 error) {
	fake.syncOutMutex.Lock()
	defer fake.syncOutMutex.Unlock()
	fake.SyncOutStub = nil
	if fake.syncOutReturnsOnCall == nil {
		fake.syncOutReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.syncOutReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMemoryBackend) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMemoryBackend) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.MemoryBackend = new(FakeMemoryBackend)
