// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	tea "charm.land/bubbletea/v2"
	"github.com/inference-gateway/cli/internal/domain"
)

type FakeApprovalCoordinator struct {
	HandleComputerUsePausedStub        func(domain.ComputerUsePausedEvent) tea.Cmd
	handleComputerUsePausedMutex       sync.RWMutex
	handleComputerUsePausedArgsForCall []struct {
		arg1 domain.ComputerUsePausedEvent
	}
	handleComputerUsePausedReturns struct {
		result1 tea.Cmd
	}
	handleComputerUsePausedReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleComputerUseResumedStub        func(domain.ComputerUseResumedEvent) (tea.Cmd, bool)
	handleComputerUseResumedMutex       sync.RWMutex
	handleComputerUseResumedArgsForCall []struct {
		arg1 domain.ComputerUseResumedEvent
	}
	handleComputerUseResumedReturns struct {
		result1 tea.Cmd
		result2 bool
	}
	handleComputerUseResumedReturnsOnCall map[int]struct {
		result1 tea.Cmd
		result2 bool
	}
	HandlePlanApprovalRequestedStub        func(domain.PlanApprovalRequestedEvent) tea.Cmd
	handlePlanApprovalRequestedMutex       sync.RWMutex
	handlePlanApprovalRequestedArgsForCall []struct {
		arg1 domain.PlanApprovalRequestedEvent
	}
	handlePlanApprovalRequestedReturns struct {
		result1 tea.Cmd
	}
	handlePlanApprovalRequestedReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandlePlanApprovalResponseStub        func(domain.PlanApprovalResponseEvent) (tea.Cmd, bool)
	handlePlanApprovalResponseMutex       sync.RWMutex
	handlePlanApprovalResponseArgsForCall []struct {
		arg1 domain.PlanApprovalResponseEvent
	}
	handlePlanApprovalResponseReturns struct {
		result1 tea.Cmd
		result2 bool
	}
	handlePlanApprovalResponseReturnsOnCall map[int]struct {
		result1 tea.Cmd
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeApprovalCoordinator) HandleComputerUsePaused(arg1 domain.ComputerUsePausedEvent) tea.Cmd {
	fake.handleComputerUsePausedMutex.Lock()
	ret, specificReturn := fake.handleComputerUsePausedReturnsOnCall[len(fake.handleComputerUsePausedArgsForCall)]
	fake.handleComputerUsePausedArgsForCall = append(fake.handleComputerUsePausedArgsForCall, struct {
		arg1 domain.ComputerUsePausedEvent
	}{arg1})
	stub := fake.HandleComputerUsePausedStub
	fakeReturns := fake.handleComputerUsePausedReturns
	fake.recordInvocation("HandleComputerUsePaused", []interface{}{arg1})
	fake.handleComputerUsePausedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeApprovalCoordinator) HandleComputerUsePausedCallCount() int {
	fake.handleComputerUsePausedMutex.RLock()
	defer fake.handleComputerUsePausedMutex.RUnlock()
	return len(fake.handleComputerUsePausedArgsForCall)
}

func (fake *FakeApprovalCoordinator) HandleComputerUsePausedCalls(stub func(domain.ComputerUsePausedEvent) tea.Cmd) {
	fake.handleComputerUsePausedMutex.Lock()
	defer fake.handleComputerUsePausedMutex.Unlock()
	fake.HandleComputerUsePausedStub = stub
}

func (fake *FakeApprovalCoordinator) HandleComputerUsePausedArgsForCall(i int) domain.ComputerUsePausedEvent {
	fake.handleComputerUsePausedMutex.RLock()
	defer fake.handleComputerUsePausedMutex.RUnlock()
	argsForCall := fake.handleComputerUsePausedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeApprovalCoordinator) HandleComputerUsePausedReturns(result1 tea.Cmd) {
	fake.handleComputerUsePausedMutex.Lock()
	defer fake.handleComputerUsePausedMutex.Unlock()
	fake.HandleComputerUsePausedStub = nil
	fake.handleComputerUsePausedReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeApprovalCoordinator) HandleComputerUsePausedReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleComputerUsePausedMutex.Lock()
	defer fake.handleComputerUsePausedMutex.Unlock()
	fake.HandleComputerUsePausedStub = nil
	if fake.handleComputerUsePausedReturnsOnCall == nil {
		fake.handleComputerUsePausedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleComputerUsePausedReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeApprovalCoordinator) HandleComputerUseResumed(arg1 domain.ComputerUseResumedEvent) (tea.Cmd, bool) {
	fake.handleComputerUseResumedMutex.Lock()
	ret, specificReturn := fake.handleComputerUseResumedReturnsOnCall[len(fake.handleComputerUseResumedArgsForCall)]
	fake.handleComputerUseResumedArgsForCall = append(fake.handleComputerUseResumedArgsForCall, struct {
		arg1 domain.ComputerUseResumedEvent
	}{arg1})
	stub := fake.HandleComputerUseResumedStub
	fakeReturns := fake.handleComputerUseResumedReturns
	fake.recordInvocation("HandleComputerUseResumed", []interface{}{arg1})
	fake.handleComputerUseResumedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeApprovalCoordinator) HandleComputerUseResumedCallCount() int {
	fake.handleComputerUseResumedMutex.RLock()
	defer fake.handleComputerUseResumedMutex.RUnlock()
	return len(fake.handleComputerUseResumedArgsForCall)
}

func (fake *FakeApprovalCoordinator) HandleComputerUseResumedCalls(stub func(domain.ComputerUseResumedEvent) (tea.Cmd, bool)) {
	fake.handleComputerUseResumedMutex.Lock()
	defer fake.handleComputerUseResumedMutex.Unlock()
	fake.HandleComputerUseResumedStub = stub
}

func (fake *FakeApprovalCoordinator) HandleComputerUseResumedArgsForCall(i int) domain.ComputerUseResumedEvent {
	fake.handleComputerUseResumedMutex.RLock()
	defer fake.handleComputerUseResumedMutex.RUnlock()
	argsForCall := fake.handleComputerUseResumedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeApprovalCoordinator) HandleComputerUseResumedReturns(result1 tea.Cmd, result2 bool) {
	fake.handleComputerUseResumedMutex.Lock()
	defer fake.handleComputerUseResumedMutex.Unlock()
	fake.HandleComputerUseResumedStub = nil
	fake.handleComputerUseResumedReturns = struct {
		result1 tea.Cmd
		result2 bool
	}{result1, result2}
}

func (fake *FakeApprovalCoordinator) HandleComputerUseResumedReturnsOnCall(i int, result1 tea.Cmd, result2 bool) {
	fake.handleComputerUseResumedMutex.Lock()
	defer fake.handleComputerUseResumedMutex.Unlock()
	fake.HandleComputerUseResumedStub = nil
	if fake.handleComputerUseResumedReturnsOnCall == nil {
		fake.handleComputerUseResumedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
			result2 bool
		})
	}
	fake.handleComputerUseResumedReturnsOnCall[i] = struct {
		result1 tea.Cmd
		result2 bool
	}{result1, result2}
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalRequested(arg1 domain.PlanApprovalRequestedEvent) tea.Cmd {
	fake.handlePlanApprovalRequestedMutex.Lock()
	ret, specificReturn := fake.handlePlanApprovalRequestedReturnsOnCall[len(fake.handlePlanApprovalRequestedArgsForCall)]
	fake.handlePlanApprovalRequestedArgsForCall = append(fake.handlePlanApprovalRequestedArgsForCall, struct {
		arg1 domain.PlanApprovalRequestedEvent
	}{arg1})
	stub := fake.HandlePlanApprovalRequestedStub
	fakeReturns := fake.handlePlanApprovalRequestedReturns
	fake.recordInvocation("HandlePlanApprovalRequested", []interface{}{arg1})
	fake.handlePlanApprovalRequestedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalRequestedCallCount() int {
	fake.handlePlanApprovalRequestedMutex.RLock()
	defer fake.handlePlanApprovalRequestedMutex.RUnlock()
	return len(fake.handlePlanApprovalRequestedArgsForCall)
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalRequestedCalls(stub func(domain.PlanApprovalRequestedEvent) tea.Cmd) {
	fake.handlePlanApprovalRequestedMutex.Lock()
	defer fake.handlePlanApprovalRequestedMutex.Unlock()
	fake.HandlePlanApprovalRequestedStub = stub
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalRequestedArgsForCall(i int) domain.PlanApprovalRequestedEvent {
	fake.handlePlanApprovalRequestedMutex.RLock()
	defer fake.handlePlanApprovalRequestedMutex.RUnlock()
	argsForCall := fake.handlePlanApprovalRequestedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalRequestedReturns(result1 tea.Cmd) {
	fake.handlePlanApprovalRequestedMutex.Lock()
	defer fake.handlePlanApprovalRequestedMutex.Unlock()
	fake.HandlePlanApprovalRequestedStub = nil
	fake.handlePlanApprovalRequestedReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalRequestedReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handlePlanApprovalRequestedMutex.Lock()
	defer fake.handlePlanApprovalRequestedMutex.Unlock()
	fake.HandlePlanApprovalRequestedStub = nil
	if fake.handlePlanApprovalRequestedReturnsOnCall == nil {
		fake.handlePlanApprovalRequestedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handlePlanApprovalRequestedReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalResponse(arg1 domain.PlanApprovalResponseEvent) (tea.Cmd, bool) {
	fake.handlePlanApprovalResponseMutex.Lock()
	ret, specificReturn := fake.handlePlanApprovalResponseReturnsOnCall[len(fake.handlePlanApprovalResponseArgsForCall)]
	fake.handlePlanApprovalResponseArgsForCall = append(fake.handlePlanApprovalResponseArgsForCall, struct {
		arg1 domain.PlanApprovalResponseEvent
	}{arg1})
	stub := fake.HandlePlanApprovalResponseStub
	fakeReturns := fake.handlePlanApprovalResponseReturns
	fake.recordInvocation("HandlePlanApprovalResponse", []interface{}{arg1})
	fake.handlePlanApprovalResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalResponseCallCount() int {
	fake.handlePlanApprovalResponseMutex.RLock()
	defer fake.handlePlanApprovalResponseMutex.RUnlock()
	return len(fake.handlePlanApprovalResponseArgsForCall)
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalResponseCalls(stub func(domain.PlanApprovalResponseEvent) (tea.Cmd, bool)) {
	fake.handlePlanApprovalResponseMutex.Lock()
	defer fake.handlePlanApprovalResponseMutex.Unlock()
	fake.HandlePlanApprovalResponseStub = stub
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalResponseArgsForCall(i int) domain.PlanApprovalResponseEvent {
	fake.handlePlanApprovalResponseMutex.RLock()
	defer fake.handlePlanApprovalResponseMutex.RUnlock()
	argsForCall := fake.handlePlanApprovalResponseArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalResponseReturns(result1 tea.Cmd, result2 bool) {
	fake.handlePlanApprovalResponseMutex.Lock()
	defer fake.handlePlanApprovalResponseMutex.Unlock()
	fake.HandlePlanApprovalResponseStub = nil
	fake.handlePlanApprovalResponseReturns = struct {
		result1 tea.Cmd
		result2 bool
	}{result1, result2}
}

func (fake *FakeApprovalCoordinator) HandlePlanApprovalResponseReturnsOnCall(i int, result1 tea.Cmd, result2 bool) {
	fake.handlePlanApprovalResponseMutex.Lock()
	defer fake.handlePlanApprovalResponseMutex.Unlock()
	fake.HandlePlanApprovalResponseStub = nil
	if fake.handlePlanApprovalResponseReturnsOnCall == nil {
		fake.handlePlanApprovalResponseReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
			result2 bool
		})
	}
	fake.handlePlanApprovalResponseReturnsOnCall[i] = struct {
		result1 tea.Cmd
		result2 bool
	}{result1, result2}
}

func (fake *FakeApprovalCoordinator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeApprovalCoordinator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.ApprovalCoordinator = new(FakeApprovalCoordinator)
