// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/inference-gateway/cli/internal/domain"
)

type FakeA2ATaskCoordinator struct {
	HandleTaskCompletedStub        func(domain.A2ATaskCompletedEvent) tea.Cmd
	handleTaskCompletedMutex       sync.RWMutex
	handleTaskCompletedArgsForCall []struct {
		arg1 domain.A2ATaskCompletedEvent
	}
	handleTaskCompletedReturns struct {
		result1 tea.Cmd
	}
	handleTaskCompletedReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleTaskFailedStub        func(domain.A2ATaskFailedEvent) tea.Cmd
	handleTaskFailedMutex       sync.RWMutex
	handleTaskFailedArgsForCall []struct {
		arg1 domain.A2ATaskFailedEvent
	}
	handleTaskFailedReturns struct {
		result1 tea.Cmd
	}
	handleTaskFailedReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleTaskInputRequiredStub        func(domain.A2ATaskInputRequiredEvent) tea.Cmd
	handleTaskInputRequiredMutex       sync.RWMutex
	handleTaskInputRequiredArgsForCall []struct {
		arg1 domain.A2ATaskInputRequiredEvent
	}
	handleTaskInputRequiredReturns struct {
		result1 tea.Cmd
	}
	handleTaskInputRequiredReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleTaskStatusUpdateStub        func(domain.A2ATaskStatusUpdateEvent) tea.Cmd
	handleTaskStatusUpdateMutex       sync.RWMutex
	handleTaskStatusUpdateArgsForCall []struct {
		arg1 domain.A2ATaskStatusUpdateEvent
	}
	handleTaskStatusUpdateReturns struct {
		result1 tea.Cmd
	}
	handleTaskStatusUpdateReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleTaskSubmittedStub        func(domain.A2ATaskSubmittedEvent) tea.Cmd
	handleTaskSubmittedMutex       sync.RWMutex
	handleTaskSubmittedArgsForCall []struct {
		arg1 domain.A2ATaskSubmittedEvent
	}
	handleTaskSubmittedReturns struct {
		result1 tea.Cmd
	}
	handleTaskSubmittedReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleToolCallExecutedStub        func(domain.A2AToolCallExecutedEvent) tea.Cmd
	handleToolCallExecutedMutex       sync.RWMutex
	handleToolCallExecutedArgsForCall []struct {
		arg1 domain.A2AToolCallExecutedEvent
	}
	handleToolCallExecutedReturns struct {
		result1 tea.Cmd
	}
	handleToolCallExecutedReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeA2ATaskCoordinator) HandleTaskCompleted(arg1 domain.A2ATaskCompletedEvent) tea.Cmd {
	fake.handleTaskCompletedMutex.Lock()
	ret, specificReturn := fake.handleTaskCompletedReturnsOnCall[len(fake.handleTaskCompletedArgsForCall)]
	fake.handleTaskCompletedArgsForCall = append(fake.handleTaskCompletedArgsForCall, struct {
		arg1 domain.A2ATaskCompletedEvent
	}{arg1})
	stub := fake.HandleTaskCompletedStub
	fakeReturns := fake.handleTaskCompletedReturns
	fake.recordInvocation("HandleTaskCompleted", []interface{}{arg1})
	fake.handleTaskCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskCompletedCallCount() int {
	fake.handleTaskCompletedMutex.RLock()
	defer fake.handleTaskCompletedMutex.RUnlock()
	return len(fake.handleTaskCompletedArgsForCall)
}

func (fake *FakeA2ATaskCoordinator) HandleTaskCompletedCalls(stub func(domain.A2ATaskCompletedEvent) tea.Cmd) {
	fake.handleTaskCompletedMutex.Lock()
	defer fake.handleTaskCompletedMutex.Unlock()
	fake.HandleTaskCompletedStub = stub
}

func (fake *FakeA2ATaskCoordinator) HandleTaskCompletedArgsForCall(i int) domain.A2ATaskCompletedEvent {
	fake.handleTaskCompletedMutex.RLock()
	defer fake.handleTaskCompletedMutex.RUnlock()
	argsForCall := fake.handleTaskCompletedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskCompletedReturns(result1 tea.Cmd) {
	fake.handleTaskCompletedMutex.Lock()
	defer fake.handleTaskCompletedMutex.Unlock()
	fake.HandleTaskCompletedStub = nil
	fake.handleTaskCompletedReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskCompletedReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleTaskCompletedMutex.Lock()
	defer fake.handleTaskCompletedMutex.Unlock()
	fake.HandleTaskCompletedStub = nil
	if fake.handleTaskCompletedReturnsOnCall == nil {
		fake.handleTaskCompletedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleTaskCompletedReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskFailed(arg1 domain.A2ATaskFailedEvent) tea.Cmd {
	fake.handleTaskFailedMutex.Lock()
	ret, specificReturn := fake.handleTaskFailedReturnsOnCall[len(fake.handleTaskFailedArgsForCall)]
	fake.handleTaskFailedArgsForCall = append(fake.handleTaskFailedArgsForCall, struct {
		arg1 domain.A2ATaskFailedEvent
	}{arg1})
	stub := fake.HandleTaskFailedStub
	fakeReturns := fake.handleTaskFailedReturns
	fake.recordInvocation("HandleTaskFailed", []interface{}{arg1})
	fake.handleTaskFailedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskFailedCallCount() int {
	fake.handleTaskFailedMutex.RLock()
	defer fake.handleTaskFailedMutex.RUnlock()
	return len(fake.handleTaskFailedArgsForCall)
}

func (fake *FakeA2ATaskCoordinator) HandleTaskFailedCalls(stub func(domain.A2ATaskFailedEvent) tea.Cmd) {
	fake.handleTaskFailedMutex.Lock()
	defer fake.handleTaskFailedMutex.Unlock()
	fake.HandleTaskFailedStub = stub
}

func (fake *FakeA2ATaskCoordinator) HandleTaskFailedArgsForCall(i int) domain.A2ATaskFailedEvent {
	fake.handleTaskFailedMutex.RLock()
	defer fake.handleTaskFailedMutex.RUnlock()
	argsForCall := fake.handleTaskFailedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskFailedReturns(result1 tea.Cmd) {
	fake.handleTaskFailedMutex.Lock()
	defer fake.handleTaskFailedMutex.Unlock()
	fake.HandleTaskFailedStub = nil
	fake.handleTaskFailedReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskFailedReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleTaskFailedMutex.Lock()
	defer fake.handleTaskFailedMutex.Unlock()
	fake.HandleTaskFailedStub = nil
	if fake.handleTaskFailedReturnsOnCall == nil {
		fake.handleTaskFailedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleTaskFailedReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskInputRequired(arg1 domain.A2ATaskInputRequiredEvent) tea.Cmd {
	fake.handleTaskInputRequiredMutex.Lock()
	ret, specificReturn := fake.handleTaskInputRequiredReturnsOnCall[len(fake.handleTaskInputRequiredArgsForCall)]
	fake.handleTaskInputRequiredArgsForCall = append(fake.handleTaskInputRequiredArgsForCall, struct {
		arg1 domain.A2ATaskInputRequiredEvent
	}{arg1})
	stub := fake.HandleTaskInputRequiredStub
	fakeReturns := fake.handleTaskInputRequiredReturns
	fake.recordInvocation("HandleTaskInputRequired", []interface{}{arg1})
	fake.handleTaskInputRequiredMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskInputRequiredCallCount() int {
	fake.handleTaskInputRequiredMutex.RLock()
	defer fake.handleTaskInputRequiredMutex.RUnlock()
	return len(fake.handleTaskInputRequiredArgsForCall)
}

func (fake *FakeA2ATaskCoordinator) HandleTaskInputRequiredCalls(stub func(domain.A2ATaskInputRequiredEvent) tea.Cmd) {
	fake.handleTaskInputRequiredMutex.Lock()
	defer fake.handleTaskInputRequiredMutex.Unlock()
	fake.HandleTaskInputRequiredStub = stub
}

func (fake *FakeA2ATaskCoordinator) HandleTaskInputRequiredArgsForCall(i int) domain.A2ATaskInputRequiredEvent {
	fake.handleTaskInputRequiredMutex.RLock()
	defer fake.handleTaskInputRequiredMutex.RUnlock()
	argsForCall := fake.handleTaskInputRequiredArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskInputRequiredReturns(result1 tea.Cmd) {
	fake.handleTaskInputRequiredMutex.Lock()
	defer fake.handleTaskInputRequiredMutex.Unlock()
	fake.HandleTaskInputRequiredStub = nil
	fake.handleTaskInputRequiredReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskInputRequiredReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleTaskInputRequiredMutex.Lock()
	defer fake.handleTaskInputRequiredMutex.Unlock()
	fake.HandleTaskInputRequiredStub = nil
	if fake.handleTaskInputRequiredReturnsOnCall == nil {
		fake.handleTaskInputRequiredReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleTaskInputRequiredReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskStatusUpdate(arg1 domain.A2ATaskStatusUpdateEvent) tea.Cmd {
	fake.handleTaskStatusUpdateMutex.Lock()
	ret, specificReturn := fake.handleTaskStatusUpdateReturnsOnCall[len(fake.handleTaskStatusUpdateArgsForCall)]
	fake.handleTaskStatusUpdateArgsForCall = append(fake.handleTaskStatusUpdateArgsForCall, struct {
		arg1 domain.A2ATaskStatusUpdateEvent
	}{arg1})
	stub := fake.HandleTaskStatusUpdateStub
	fakeReturns := fake.handleTaskStatusUpdateReturns
	fake.recordInvocation("HandleTaskStatusUpdate", []interface{}{arg1})
	fake.handleTaskStatusUpdateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskStatusUpdateCallCount() int {
	fake.handleTaskStatusUpdateMutex.RLock()
	defer fake.handleTaskStatusUpdateMutex.RUnlock()
	return len(fake.handleTaskStatusUpdateArgsForCall)
}

func (fake *FakeA2ATaskCoordinator) HandleTaskStatusUpdateCalls(stub func(domain.A2ATaskStatusUpdateEvent) tea.Cmd) {
	fake.handleTaskStatusUpdateMutex.Lock()
	defer fake.handleTaskStatusUpdateMutex.Unlock()
	fake.HandleTaskStatusUpdateStub = stub
}

func (fake *FakeA2ATaskCoordinator) HandleTaskStatusUpdateArgsForCall(i int) domain.A2ATaskStatusUpdateEvent {
	fake.handleTaskStatusUpdateMutex.RLock()
	defer fake.handleTaskStatusUpdateMutex.RUnlock()
	argsForCall := fake.handleTaskStatusUpdateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskStatusUpdateReturns(result1 tea.Cmd) {
	fake.handleTaskStatusUpdateMutex.Lock()
	defer fake.handleTaskStatusUpdateMutex.Unlock()
	fake.HandleTaskStatusUpdateStub = nil
	fake.handleTaskStatusUpdateReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskStatusUpdateReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleTaskStatusUpdateMutex.Lock()
	defer fake.handleTaskStatusUpdateMutex.Unlock()
	fake.HandleTaskStatusUpdateStub = nil
	if fake.handleTaskStatusUpdateReturnsOnCall == nil {
		fake.handleTaskStatusUpdateReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleTaskStatusUpdateReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskSubmitted(arg1 domain.A2ATaskSubmittedEvent) tea.Cmd {
	fake.handleTaskSubmittedMutex.Lock()
	ret, specificReturn := fake.handleTaskSubmittedReturnsOnCall[len(fake.handleTaskSubmittedArgsForCall)]
	fake.handleTaskSubmittedArgsForCall = append(fake.handleTaskSubmittedArgsForCall, struct {
		arg1 domain.A2ATaskSubmittedEvent
	}{arg1})
	stub := fake.HandleTaskSubmittedStub
	fakeReturns := fake.handleTaskSubmittedReturns
	fake.recordInvocation("HandleTaskSubmitted", []interface{}{arg1})
	fake.handleTaskSubmittedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskSubmittedCallCount() int {
	fake.handleTaskSubmittedMutex.RLock()
	defer fake.handleTaskSubmittedMutex.RUnlock()
	return len(fake.handleTaskSubmittedArgsForCall)
}

func (fake *FakeA2ATaskCoordinator) HandleTaskSubmittedCalls(stub func(domain.A2ATaskSubmittedEvent) tea.Cmd) {
	fake.handleTaskSubmittedMutex.Lock()
	defer fake.handleTaskSubmittedMutex.Unlock()
	fake.HandleTaskSubmittedStub = stub
}

func (fake *FakeA2ATaskCoordinator) HandleTaskSubmittedArgsForCall(i int) domain.A2ATaskSubmittedEvent {
	fake.handleTaskSubmittedMutex.RLock()
	defer fake.handleTaskSubmittedMutex.RUnlock()
	argsForCall := fake.handleTaskSubmittedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskCoordinator) HandleTaskSubmittedReturns(result1 tea.Cmd) {
	fake.handleTaskSubmittedMutex.Lock()
	defer fake.handleTaskSubmittedMutex.Unlock()
	fake.HandleTaskSubmittedStub = nil
	fake.handleTaskSubmittedReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleTaskSubmittedReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleTaskSubmittedMutex.Lock()
	defer fake.handleTaskSubmittedMutex.Unlock()
	fake.HandleTaskSubmittedStub = nil
	if fake.handleTaskSubmittedReturnsOnCall == nil {
		fake.handleTaskSubmittedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleTaskSubmittedReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleToolCallExecuted(arg1 domain.A2AToolCallExecutedEvent) tea.Cmd {
	fake.handleToolCallExecutedMutex.Lock()
	ret, specificReturn := fake.handleToolCallExecutedReturnsOnCall[len(fake.handleToolCallExecutedArgsForCall)]
	fake.handleToolCallExecutedArgsForCall = append(fake.handleToolCallExecutedArgsForCall, struct {
		arg1 domain.A2AToolCallExecutedEvent
	}{arg1})
	stub := fake.HandleToolCallExecutedStub
	fakeReturns := fake.handleToolCallExecutedReturns
	fake.recordInvocation("HandleToolCallExecuted", []interface{}{arg1})
	fake.handleToolCallExecutedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskCoordinator) HandleToolCallExecutedCallCount() int {
	fake.handleToolCallExecutedMutex.RLock()
	defer fake.handleToolCallExecutedMutex.RUnlock()
	return len(fake.handleToolCallExecutedArgsForCall)
}

func (fake *FakeA2ATaskCoordinator) HandleToolCallExecutedCalls(stub func(domain.A2AToolCallExecutedEvent) tea.Cmd) {
	fake.handleToolCallExecutedMutex.Lock()
	defer fake.handleToolCallExecutedMutex.Unlock()
	fake.HandleToolCallExecutedStub = stub
}

func (fake *FakeA2ATaskCoordinator) HandleToolCallExecutedArgsForCall(i int) domain.A2AToolCallExecutedEvent {
	fake.handleToolCallExecutedMutex.RLock()
	defer fake.handleToolCallExecutedMutex.RUnlock()
	argsForCall := fake.handleToolCallExecutedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskCoordinator) HandleToolCallExecutedReturns(result1 tea.Cmd) {
	fake.handleToolCallExecutedMutex.Lock()
	defer fake.handleToolCallExecutedMutex.Unlock()
	fake.HandleToolCallExecutedStub = nil
	fake.handleToolCallExecutedReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) HandleToolCallExecutedReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleToolCallExecutedMutex.Lock()
	defer fake.handleToolCallExecutedMutex.Unlock()
	fake.HandleToolCallExecutedStub = nil
	if fake.handleToolCallExecutedReturnsOnCall == nil {
		fake.handleToolCallExecutedReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleToolCallExecutedReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeA2ATaskCoordinator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeA2ATaskCoordinator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.A2ATaskCoordinator = new(FakeA2ATaskCoordinator)
