// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeBashDetachChannelHolder struct {
	ClearBashDetachChanStub        func()
	clearBashDetachChanMutex       sync.RWMutex
	clearBashDetachChanArgsForCall []struct {
	}
	GetBashDetachChanStub        func() chan<- struct{}
	getBashDetachChanMutex       sync.RWMutex
	getBashDetachChanArgsForCall []struct {
	}
	getBashDetachChanReturns struct {
		result1 chan<- struct{}
	}
	getBashDetachChanReturnsOnCall map[int]struct {
		result1 chan<- struct{}
	}
	SetBashDetachChanStub        func(chan<- struct{})
	setBashDetachChanMutex       sync.RWMutex
	setBashDetachChanArgsForCall []struct {
		arg1 chan<- struct{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBashDetachChannelHolder) ClearBashDetachChan() {
	fake.clearBashDetachChanMutex.Lock()
	fake.clearBashDetachChanArgsForCall = append(fake.clearBashDetachChanArgsForCall, struct {
	}{})
	stub := fake.ClearBashDetachChanStub
	fake.recordInvocation("ClearBashDetachChan", []interface{}{})
	fake.clearBashDetachChanMutex.Unlock()
	if stub != nil {
		fake.ClearBashDetachChanStub()
	}
}

func (fake *FakeBashDetachChannelHolder) ClearBashDetachChanCallCount() int {
	fake.clearBashDetachChanMutex.RLock()
	defer fake.clearBashDetachChanMutex.RUnlock()
	return len(fake.clearBashDetachChanArgsForCall)
}

func (fake *FakeBashDetachChannelHolder) ClearBashDetachChanCalls(stub func()) {
	fake.clearBashDetachChanMutex.Lock()
	defer fake.clearBashDetachChanMutex.Unlock()
	fake.ClearBashDetachChanStub = stub
}

func (fake *FakeBashDetachChannelHolder) GetBashDetachChan() chan<- struct{} {
	fake.getBashDetachChanMutex.Lock()
	ret, specificReturn := fake.getBashDetachChanReturnsOnCall[len(fake.getBashDetachChanArgsForCall)]
	fake.getBashDetachChanArgsForCall = append(fake.getBashDetachChanArgsForCall, struct {
	}{})
	stub := fake.GetBashDetachChanStub
	fakeReturns := fake.getBashDetachChanReturns
	fake.recordInvocation("GetBashDetachChan", []interface{}{})
	fake.getBashDetachChanMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBashDetachChannelHolder) GetBashDetachChanCallCount() int {
	fake.getBashDetachChanMutex.RLock()
	defer fake.getBashDetachChanMutex.RUnlock()
	return len(fake.getBashDetachChanArgsForCall)
}

func (fake *FakeBashDetachChannelHolder) GetBashDetachChanCalls(stub func() chan<- struct{}) {
	fake.getBashDetachChanMutex.Lock()
	defer fake.getBashDetachChanMutex.Unlock()
	fake.GetBashDetachChanStub = stub
}

func (fake *FakeBashDetachChannelHolder) GetBashDetachChanReturns(result1 chan<- struct{}) {
	fake.getBashDetachChanMutex.Lock()
	defer fake.getBashDetachChanMutex.Unlock()
	fake.GetBashDetachChanStub = nil
	fake.getBashDetachChanReturns = struct {
		result1 chan<- struct{}
	}{result1}
}

func (fake *FakeBashDetachChannelHolder) GetBashDetachChanReturnsOnCall(i int, result1 chan<- struct{}) {
	fake.getBashDetachChanMutex.Lock()
	defer fake.getBashDetachChanMutex.Unlock()
	fake.GetBashDetachChanStub = nil
	if fake.getBashDetachChanReturnsOnCall == nil {
		fake.getBashDetachChanReturnsOnCall = make(map[int]struct {
			result1 chan<- struct{}
		})
	}
	fake.getBashDetachChanReturnsOnCall[i] = struct {
		result1 chan<- struct{}
	}{result1}
}

func (fake *FakeBashDetachChannelHolder) SetBashDetachChan(arg1 chan<- struct{}) {
	fake.setBashDetachChanMutex.Lock()
	fake.setBashDetachChanArgsForCall = append(fake.setBashDetachChanArgsForCall, struct {
		arg1 chan<- struct{}
	}{arg1})
	stub := fake.SetBashDetachChanStub
	fake.recordInvocation("SetBashDetachChan", []interface{}{arg1})
	fake.setBashDetachChanMutex.Unlock()
	if stub != nil {
		fake.SetBashDetachChanStub(arg1)
	}
}

func (fake *FakeBashDetachChannelHolder) SetBashDetachChanCallCount() int {
	fake.setBashDetachChanMutex.RLock()
	defer fake.setBashDetachChanMutex.RUnlock()
	return len(fake.setBashDetachChanArgsForCall)
}

func (fake *FakeBashDetachChannelHolder) SetBashDetachChanCalls(stub func(chan<- struct{})) {
	fake.setBashDetachChanMutex.Lock()
	defer fake.setBashDetachChanMutex.Unlock()
	fake.SetBashDetachChanStub = stub
}

func (fake *FakeBashDetachChannelHolder) SetBashDetachChanArgsForCall(i int) chan<- struct{} {
	fake.setBashDetachChanMutex.RLock()
	defer fake.setBashDetachChanMutex.RUnlock()
	argsForCall := fake.setBashDetachChanArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBashDetachChannelHolder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBashDetachChannelHolder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.BashDetachChannelHolder = new(FakeBashDetachChannelHolder)
