// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
	"github.com/inference-gateway/sdk"
)

type FakeApprovalPolicy struct {
	ShouldRequireApprovalStub        func(context.Context, *sdk.ChatCompletionMessageToolCall, bool) bool
	shouldRequireApprovalMutex       sync.RWMutex
	shouldRequireApprovalArgsForCall []struct {
		arg1 context.Context
		arg2 *sdk.ChatCompletionMessageToolCall
		arg3 bool
	}
	shouldRequireApprovalReturns struct {
		result1 bool
	}
	shouldRequireApprovalReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeApprovalPolicy) ShouldRequireApproval(arg1 context.Context, arg2 *sdk.ChatCompletionMessageToolCall, arg3 bool) bool {
	fake.shouldRequireApprovalMutex.Lock()
	ret, specificReturn := fake.shouldRequireApprovalReturnsOnCall[len(fake.shouldRequireApprovalArgsForCall)]
	fake.shouldRequireApprovalArgsForCall = append(fake.shouldRequireApprovalArgsForCall, struct {
		arg1 context.Context
		arg2 *sdk.ChatCompletionMessageToolCall
		arg3 bool
	}{arg1, arg2, arg3})
	stub := fake.ShouldRequireApprovalStub
	fakeReturns := fake.shouldRequireApprovalReturns
	fake.recordInvocation("ShouldRequireApproval", []interface{}{arg1, arg2, arg3})
	fake.shouldRequireApprovalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeApprovalPolicy) ShouldRequireApprovalCallCount() int {
	fake.shouldRequireApprovalMutex.RLock()
	defer fake.shouldRequireApprovalMutex.RUnlock()
	return len(fake.shouldRequireApprovalArgsForCall)
}

func (fake *FakeApprovalPolicy) ShouldRequireApprovalCalls(stub func(context.Context, *sdk.ChatCompletionMessageToolCall, bool) bool) {
	fake.shouldRequireApprovalMutex.Lock()
	defer fake.shouldRequireApprovalMutex.Unlock()
	fake.ShouldRequireApprovalStub = stub
}

func (fake *FakeApprovalPolicy) ShouldRequireApprovalArgsForCall(i int) (context.Context, *sdk.ChatCompletionMessageToolCall, bool) {
	fake.shouldRequireApprovalMutex.RLock()
	defer fake.shouldRequireApprovalMutex.RUnlock()
	argsForCall := fake.shouldRequireApprovalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeApprovalPolicy) ShouldRequireApprovalReturns(result1 bool) {
	fake.shouldRequireApprovalMutex.Lock()
	defer fake.shouldRequireApprovalMutex.Unlock()
	fake.ShouldRequireApprovalStub = nil
	fake.shouldRequireApprovalReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeApprovalPolicy) ShouldRequireApprovalReturnsOnCall(i int, result1 bool) {
	fake.shouldRequireApprovalMutex.Lock()
	defer fake.shouldRequireApprovalMutex.Unlock()
	fake.ShouldRequireApprovalStub = nil
	if fake.shouldRequireApprovalReturnsOnCall == nil {
		fake.shouldRequireApprovalReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.shouldRequireApprovalReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeApprovalPolicy) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeApprovalPolicy) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.ApprovalPolicy = new(FakeApprovalPolicy)
