// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	tea "charm.land/bubbletea/v2"
	"github.com/inference-gateway/cli/internal/domain"
)

type FakeChatCompletionRunner struct {
	HandleChatChunkStub        func(domain.ChatChunkEvent) tea.Cmd
	handleChatChunkMutex       sync.RWMutex
	handleChatChunkArgsForCall []struct {
		arg1 domain.ChatChunkEvent
	}
	handleChatChunkReturns struct {
		result1 tea.Cmd
	}
	handleChatChunkReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleChatCompleteStub        func(domain.ChatCompleteEvent) tea.Cmd
	handleChatCompleteMutex       sync.RWMutex
	handleChatCompleteArgsForCall []struct {
		arg1 domain.ChatCompleteEvent
	}
	handleChatCompleteReturns struct {
		result1 tea.Cmd
	}
	handleChatCompleteReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleChatErrorStub        func(domain.ChatErrorEvent) tea.Cmd
	handleChatErrorMutex       sync.RWMutex
	handleChatErrorArgsForCall []struct {
		arg1 domain.ChatErrorEvent
	}
	handleChatErrorReturns struct {
		result1 tea.Cmd
	}
	handleChatErrorReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleChatStartStub        func(domain.ChatStartEvent) tea.Cmd
	handleChatStartMutex       sync.RWMutex
	handleChatStartArgsForCall []struct {
		arg1 domain.ChatStartEvent
	}
	handleChatStartReturns struct {
		result1 tea.Cmd
	}
	handleChatStartReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	HandleOptimizationStatusStub        func(domain.OptimizationStatusEvent) tea.Cmd
	handleOptimizationStatusMutex       sync.RWMutex
	handleOptimizationStatusArgsForCall []struct {
		arg1 domain.OptimizationStatusEvent
	}
	handleOptimizationStatusReturns struct {
		result1 tea.Cmd
	}
	handleOptimizationStatusReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	SetPendingRestorationStub        func(string)
	setPendingRestorationMutex       sync.RWMutex
	setPendingRestorationArgsForCall []struct {
		arg1 string
	}
	StartStub        func(domain.BashDetachChannelHolder) tea.Cmd
	startMutex       sync.RWMutex
	startArgsForCall []struct {
		arg1 domain.BashDetachChannelHolder
	}
	startReturns struct {
		result1 tea.Cmd
	}
	startReturnsOnCall map[int]struct {
		result1 tea.Cmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChatCompletionRunner) HandleChatChunk(arg1 domain.ChatChunkEvent) tea.Cmd {
	fake.handleChatChunkMutex.Lock()
	ret, specificReturn := fake.handleChatChunkReturnsOnCall[len(fake.handleChatChunkArgsForCall)]
	fake.handleChatChunkArgsForCall = append(fake.handleChatChunkArgsForCall, struct {
		arg1 domain.ChatChunkEvent
	}{arg1})
	stub := fake.HandleChatChunkStub
	fakeReturns := fake.handleChatChunkReturns
	fake.recordInvocation("HandleChatChunk", []interface{}{arg1})
	fake.handleChatChunkMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChatCompletionRunner) HandleChatChunkCallCount() int {
	fake.handleChatChunkMutex.RLock()
	defer fake.handleChatChunkMutex.RUnlock()
	return len(fake.handleChatChunkArgsForCall)
}

func (fake *FakeChatCompletionRunner) HandleChatChunkCalls(stub func(domain.ChatChunkEvent) tea.Cmd) {
	fake.handleChatChunkMutex.Lock()
	defer fake.handleChatChunkMutex.Unlock()
	fake.HandleChatChunkStub = stub
}

func (fake *FakeChatCompletionRunner) HandleChatChunkArgsForCall(i int) domain.ChatChunkEvent {
	fake.handleChatChunkMutex.RLock()
	defer fake.handleChatChunkMutex.RUnlock()
	argsForCall := fake.handleChatChunkArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) HandleChatChunkReturns(result1 tea.Cmd) {
	fake.handleChatChunkMutex.Lock()
	defer fake.handleChatChunkMutex.Unlock()
	fake.HandleChatChunkStub = nil
	fake.handleChatChunkReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatChunkReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleChatChunkMutex.Lock()
	defer fake.handleChatChunkMutex.Unlock()
	fake.HandleChatChunkStub = nil
	if fake.handleChatChunkReturnsOnCall == nil {
		fake.handleChatChunkReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleChatChunkReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatComplete(arg1 domain.ChatCompleteEvent) tea.Cmd {
	fake.handleChatCompleteMutex.Lock()
	ret, specificReturn := fake.handleChatCompleteReturnsOnCall[len(fake.handleChatCompleteArgsForCall)]
	fake.handleChatCompleteArgsForCall = append(fake.handleChatCompleteArgsForCall, struct {
		arg1 domain.ChatCompleteEvent
	}{arg1})
	stub := fake.HandleChatCompleteStub
	fakeReturns := fake.handleChatCompleteReturns
	fake.recordInvocation("HandleChatComplete", []interface{}{arg1})
	fake.handleChatCompleteMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChatCompletionRunner) HandleChatCompleteCallCount() int {
	fake.handleChatCompleteMutex.RLock()
	defer fake.handleChatCompleteMutex.RUnlock()
	return len(fake.handleChatCompleteArgsForCall)
}

func (fake *FakeChatCompletionRunner) HandleChatCompleteCalls(stub func(domain.ChatCompleteEvent) tea.Cmd) {
	fake.handleChatCompleteMutex.Lock()
	defer fake.handleChatCompleteMutex.Unlock()
	fake.HandleChatCompleteStub = stub
}

func (fake *FakeChatCompletionRunner) HandleChatCompleteArgsForCall(i int) domain.ChatCompleteEvent {
	fake.handleChatCompleteMutex.RLock()
	defer fake.handleChatCompleteMutex.RUnlock()
	argsForCall := fake.handleChatCompleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) HandleChatCompleteReturns(result1 tea.Cmd) {
	fake.handleChatCompleteMutex.Lock()
	defer fake.handleChatCompleteMutex.Unlock()
	fake.HandleChatCompleteStub = nil
	fake.handleChatCompleteReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatCompleteReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleChatCompleteMutex.Lock()
	defer fake.handleChatCompleteMutex.Unlock()
	fake.HandleChatCompleteStub = nil
	if fake.handleChatCompleteReturnsOnCall == nil {
		fake.handleChatCompleteReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleChatCompleteReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatError(arg1 domain.ChatErrorEvent) tea.Cmd {
	fake.handleChatErrorMutex.Lock()
	ret, specificReturn := fake.handleChatErrorReturnsOnCall[len(fake.handleChatErrorArgsForCall)]
	fake.handleChatErrorArgsForCall = append(fake.handleChatErrorArgsForCall, struct {
		arg1 domain.ChatErrorEvent
	}{arg1})
	stub := fake.HandleChatErrorStub
	fakeReturns := fake.handleChatErrorReturns
	fake.recordInvocation("HandleChatError", []interface{}{arg1})
	fake.handleChatErrorMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChatCompletionRunner) HandleChatErrorCallCount() int {
	fake.handleChatErrorMutex.RLock()
	defer fake.handleChatErrorMutex.RUnlock()
	return len(fake.handleChatErrorArgsForCall)
}

func (fake *FakeChatCompletionRunner) HandleChatErrorCalls(stub func(domain.ChatErrorEvent) tea.Cmd) {
	fake.handleChatErrorMutex.Lock()
	defer fake.handleChatErrorMutex.Unlock()
	fake.HandleChatErrorStub = stub
}

func (fake *FakeChatCompletionRunner) HandleChatErrorArgsForCall(i int) domain.ChatErrorEvent {
	fake.handleChatErrorMutex.RLock()
	defer fake.handleChatErrorMutex.RUnlock()
	argsForCall := fake.handleChatErrorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) HandleChatErrorReturns(result1 tea.Cmd) {
	fake.handleChatErrorMutex.Lock()
	defer fake.handleChatErrorMutex.Unlock()
	fake.HandleChatErrorStub = nil
	fake.handleChatErrorReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatErrorReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleChatErrorMutex.Lock()
	defer fake.handleChatErrorMutex.Unlock()
	fake.HandleChatErrorStub = nil
	if fake.handleChatErrorReturnsOnCall == nil {
		fake.handleChatErrorReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleChatErrorReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatStart(arg1 domain.ChatStartEvent) tea.Cmd {
	fake.handleChatStartMutex.Lock()
	ret, specificReturn := fake.handleChatStartReturnsOnCall[len(fake.handleChatStartArgsForCall)]
	fake.handleChatStartArgsForCall = append(fake.handleChatStartArgsForCall, struct {
		arg1 domain.ChatStartEvent
	}{arg1})
	stub := fake.HandleChatStartStub
	fakeReturns := fake.handleChatStartReturns
	fake.recordInvocation("HandleChatStart", []interface{}{arg1})
	fake.handleChatStartMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChatCompletionRunner) HandleChatStartCallCount() int {
	fake.handleChatStartMutex.RLock()
	defer fake.handleChatStartMutex.RUnlock()
	return len(fake.handleChatStartArgsForCall)
}

func (fake *FakeChatCompletionRunner) HandleChatStartCalls(stub func(domain.ChatStartEvent) tea.Cmd) {
	fake.handleChatStartMutex.Lock()
	defer fake.handleChatStartMutex.Unlock()
	fake.HandleChatStartStub = stub
}

func (fake *FakeChatCompletionRunner) HandleChatStartArgsForCall(i int) domain.ChatStartEvent {
	fake.handleChatStartMutex.RLock()
	defer fake.handleChatStartMutex.RUnlock()
	argsForCall := fake.handleChatStartArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) HandleChatStartReturns(result1 tea.Cmd) {
	fake.handleChatStartMutex.Lock()
	defer fake.handleChatStartMutex.Unlock()
	fake.HandleChatStartStub = nil
	fake.handleChatStartReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleChatStartReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleChatStartMutex.Lock()
	defer fake.handleChatStartMutex.Unlock()
	fake.HandleChatStartStub = nil
	if fake.handleChatStartReturnsOnCall == nil {
		fake.handleChatStartReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleChatStartReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleOptimizationStatus(arg1 domain.OptimizationStatusEvent) tea.Cmd {
	fake.handleOptimizationStatusMutex.Lock()
	ret, specificReturn := fake.handleOptimizationStatusReturnsOnCall[len(fake.handleOptimizationStatusArgsForCall)]
	fake.handleOptimizationStatusArgsForCall = append(fake.handleOptimizationStatusArgsForCall, struct {
		arg1 domain.OptimizationStatusEvent
	}{arg1})
	stub := fake.HandleOptimizationStatusStub
	fakeReturns := fake.handleOptimizationStatusReturns
	fake.recordInvocation("HandleOptimizationStatus", []interface{}{arg1})
	fake.handleOptimizationStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChatCompletionRunner) HandleOptimizationStatusCallCount() int {
	fake.handleOptimizationStatusMutex.RLock()
	defer fake.handleOptimizationStatusMutex.RUnlock()
	return len(fake.handleOptimizationStatusArgsForCall)
}

func (fake *FakeChatCompletionRunner) HandleOptimizationStatusCalls(stub func(domain.OptimizationStatusEvent) tea.Cmd) {
	fake.handleOptimizationStatusMutex.Lock()
	defer fake.handleOptimizationStatusMutex.Unlock()
	fake.HandleOptimizationStatusStub = stub
}

func (fake *FakeChatCompletionRunner) HandleOptimizationStatusArgsForCall(i int) domain.OptimizationStatusEvent {
	fake.handleOptimizationStatusMutex.RLock()
	defer fake.handleOptimizationStatusMutex.RUnlock()
	argsForCall := fake.handleOptimizationStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) HandleOptimizationStatusReturns(result1 tea.Cmd) {
	fake.handleOptimizationStatusMutex.Lock()
	defer fake.handleOptimizationStatusMutex.Unlock()
	fake.HandleOptimizationStatusStub = nil
	fake.handleOptimizationStatusReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) HandleOptimizationStatusReturnsOnCall(i int, result1 tea.Cmd) {
	fake.handleOptimizationStatusMutex.Lock()
	defer fake.handleOptimizationStatusMutex.Unlock()
	fake.HandleOptimizationStatusStub = nil
	if fake.handleOptimizationStatusReturnsOnCall == nil {
		fake.handleOptimizationStatusReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.handleOptimizationStatusReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) SetPendingRestoration(arg1 string) {
	fake.setPendingRestorationMutex.Lock()
	fake.setPendingRestorationArgsForCall = append(fake.setPendingRestorationArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetPendingRestorationStub
	fake.recordInvocation("SetPendingRestoration", []interface{}{arg1})
	fake.setPendingRestorationMutex.Unlock()
	if stub != nil {
		fake.SetPendingRestorationStub(arg1)
	}
}

func (fake *FakeChatCompletionRunner) SetPendingRestorationCallCount() int {
	fake.setPendingRestorationMutex.RLock()
	defer fake.setPendingRestorationMutex.RUnlock()
	return len(fake.setPendingRestorationArgsForCall)
}

func (fake *FakeChatCompletionRunner) SetPendingRestorationCalls(stub func(string)) {
	fake.setPendingRestorationMutex.Lock()
	defer fake.setPendingRestorationMutex.Unlock()
	fake.SetPendingRestorationStub = stub
}

func (fake *FakeChatCompletionRunner) SetPendingRestorationArgsForCall(i int) string {
	fake.setPendingRestorationMutex.RLock()
	defer fake.setPendingRestorationMutex.RUnlock()
	argsForCall := fake.setPendingRestorationArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) Start(arg1 domain.BashDetachChannelHolder) tea.Cmd {
	fake.startMutex.Lock()
	ret, specificReturn := fake.startReturnsOnCall[len(fake.startArgsForCall)]
	fake.startArgsForCall = append(fake.startArgsForCall, struct {
		arg1 domain.BashDetachChannelHolder
	}{arg1})
	stub := fake.StartStub
	fakeReturns := fake.startReturns
	fake.recordInvocation("Start", []interface{}{arg1})
	fake.startMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChatCompletionRunner) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

func (fake *FakeChatCompletionRunner) StartCalls(stub func(domain.BashDetachChannelHolder) tea.Cmd) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = stub
}

func (fake *FakeChatCompletionRunner) StartArgsForCall(i int) domain.BashDetachChannelHolder {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	argsForCall := fake.startArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChatCompletionRunner) StartReturns(result1 tea.Cmd) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = nil
	fake.startReturns = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) StartReturnsOnCall(i int, result1 tea.Cmd) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = nil
	if fake.startReturnsOnCall == nil {
		fake.startReturnsOnCall = make(map[int]struct {
			result1 tea.Cmd
		})
	}
	fake.startReturnsOnCall[i] = struct {
		result1 tea.Cmd
	}{result1}
}

func (fake *FakeChatCompletionRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChatCompletionRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.ChatCompletionRunner = new(FakeChatCompletionRunner)
