// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeA2ATaskTracker struct {
	AddTaskStub        func(string, string)
	addTaskMutex       sync.RWMutex
	addTaskArgsForCall []struct {
		arg1 string
		arg2 string
	}
	ClearAllAgentsStub        func()
	clearAllAgentsMutex       sync.RWMutex
	clearAllAgentsArgsForCall []struct {
	}
	GetAllPollingTasksStub        func() []string
	getAllPollingTasksMutex       sync.RWMutex
	getAllPollingTasksArgsForCall []struct {
	}
	getAllPollingTasksReturns struct {
		result1 []string
	}
	getAllPollingTasksReturnsOnCall map[int]struct {
		result1 []string
	}
	GetLatestContextForAgentStub        func(string) string
	getLatestContextForAgentMutex       sync.RWMutex
	getLatestContextForAgentArgsForCall []struct {
		arg1 string
	}
	getLatestContextForAgentReturns struct {
		result1 string
	}
	getLatestContextForAgentReturnsOnCall map[int]struct {
		result1 string
	}
	GetLatestTaskForContextStub        func(string) string
	getLatestTaskForContextMutex       sync.RWMutex
	getLatestTaskForContextArgsForCall []struct {
		arg1 string
	}
	getLatestTaskForContextReturns struct {
		result1 string
	}
	getLatestTaskForContextReturnsOnCall map[int]struct {
		result1 string
	}
	GetPollingStateStub        func(string) *domain.TaskPollingState
	getPollingStateMutex       sync.RWMutex
	getPollingStateArgsForCall []struct {
		arg1 string
	}
	getPollingStateReturns struct {
		result1 *domain.TaskPollingState
	}
	getPollingStateReturnsOnCall map[int]struct {
		result1 *domain.TaskPollingState
	}
	HasContextStub        func(string) bool
	hasContextMutex       sync.RWMutex
	hasContextArgsForCall []struct {
		arg1 string
	}
	hasContextReturns struct {
		result1 bool
	}
	hasContextReturnsOnCall map[int]struct {
		result1 bool
	}
	RegisterContextStub        func(string, string)
	registerContextMutex       sync.RWMutex
	registerContextArgsForCall []struct {
		arg1 string
		arg2 string
	}
	RemoveTaskStub        func(string)
	removeTaskMutex       sync.RWMutex
	removeTaskArgsForCall []struct {
		arg1 string
	}
	StartPollingStub        func(string, *domain.TaskPollingState)
	startPollingMutex       sync.RWMutex
	startPollingArgsForCall []struct {
		arg1 string
		arg2 *domain.TaskPollingState
	}
	StopPollingStub        func(string)
	stopPollingMutex       sync.RWMutex
	stopPollingArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeA2ATaskTracker) AddTask(arg1 string, arg2 string) {
	fake.addTaskMutex.Lock()
	fake.addTaskArgsForCall = append(fake.addTaskArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.AddTaskStub
	fake.recordInvocation("AddTask", []interface{}{arg1, arg2})
	fake.addTaskMutex.Unlock()
	if stub != nil {
		fake.AddTaskStub(arg1, arg2)
	}
}

func (fake *FakeA2ATaskTracker) AddTaskCallCount() int {
	fake.addTaskMutex.RLock()
	defer fake.addTaskMutex.RUnlock()
	return len(fake.addTaskArgsForCall)
}

func (fake *FakeA2ATaskTracker) AddTaskCalls(stub func(string, string)) {
	fake.addTaskMutex.Lock()
	defer fake.addTaskMutex.Unlock()
	fake.AddTaskStub = stub
}

func (fake *FakeA2ATaskTracker) AddTaskArgsForCall(i int) (string, string) {
	fake.addTaskMutex.RLock()
	defer fake.addTaskMutex.RUnlock()
	argsForCall := fake.addTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2ATaskTracker) ClearAllAgents() {
	fake.clearAllAgentsMutex.Lock()
	fake.clearAllAgentsArgsForCall = append(fake.clearAllAgentsArgsForCall, struct {
	}{})
	stub := fake.ClearAllAgentsStub
	fake.recordInvocation("ClearAllAgents", []interface{}{})
	fake.clearAllAgentsMutex.Unlock()
	if stub != nil {
		fake.ClearAllAgentsStub()
	}
}

func (fake *FakeA2ATaskTracker) ClearAllAgentsCallCount() int {
	fake.clearAllAgentsMutex.RLock()
	defer fake.clearAllAgentsMutex.RUnlock()
	return len(fake.clearAllAgentsArgsForCall)
}

func (fake *FakeA2ATaskTracker) ClearAllAgentsCalls(stub func()) {
	fake.clearAllAgentsMutex.Lock()
	defer fake.clearAllAgentsMutex.Unlock()
	fake.ClearAllAgentsStub = stub
}

func (fake *FakeA2ATaskTracker) GetAllPollingTasks() []string {
	fake.getAllPollingTasksMutex.Lock()
	ret, specificReturn := fake.getAllPollingTasksReturnsOnCall[len(fake.getAllPollingTasksArgsForCall)]
	fake.getAllPollingTasksArgsForCall = append(fake.getAllPollingTasksArgsForCall, struct {
	}{})
	stub := fake.GetAllPollingTasksStub
	fakeReturns := fake.getAllPollingTasksReturns
	fake.recordInvocation("GetAllPollingTasks", []interface{}{})
	fake.getAllPollingTasksMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskTracker) GetAllPollingTasksCallCount() int {
	fake.getAllPollingTasksMutex.RLock()
	defer fake.getAllPollingTasksMutex.RUnlock()
	return len(fake.getAllPollingTasksArgsForCall)
}

func (fake *FakeA2ATaskTracker) GetAllPollingTasksCalls(stub func() []string) {
	fake.getAllPollingTasksMutex.Lock()
	defer fake.getAllPollingTasksMutex.Unlock()
	fake.GetAllPollingTasksStub = stub
}

func (fake *FakeA2ATaskTracker) GetAllPollingTasksReturns(result1 []string) {
	fake.getAllPollingTasksMutex.Lock()
	defer fake.getAllPollingTasksMutex.Unlock()
	fake.GetAllPollingTasksStub = nil
	fake.getAllPollingTasksReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetAllPollingTasksReturnsOnCall(i int, result1 []string) {
	fake.getAllPollingTasksMutex.Lock()
	defer fake.getAllPollingTasksMutex.Unlock()
	fake.GetAllPollingTasksStub = nil
	if fake.getAllPollingTasksReturnsOnCall == nil {
		fake.getAllPollingTasksReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getAllPollingTasksReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetLatestContextForAgent(arg1 string) string {
	fake.getLatestContextForAgentMutex.Lock()
	ret, specificReturn := fake.getLatestContextForAgentReturnsOnCall[len(fake.getLatestContextForAgentArgsForCall)]
	fake.getLatestContextForAgentArgsForCall = append(fake.getLatestContextForAgentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetLatestContextForAgentStub
	fakeReturns := fake.getLatestContextForAgentReturns
	fake.recordInvocation("GetLatestContextForAgent", []interface{}{arg1})
	fake.getLatestContextForAgentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskTracker) GetLatestContextForAgentCallCount() int {
	fake.getLatestContextForAgentMutex.RLock()
	defer fake.getLatestContextForAgentMutex.RUnlock()
	return len(fake.getLatestContextForAgentArgsForCall)
}

func (fake *FakeA2ATaskTracker) GetLatestContextForAgentCalls(stub func(string) string) {
	fake.getLatestContextForAgentMutex.Lock()
	defer fake.getLatestContextForAgentMutex.Unlock()
	fake.GetLatestContextForAgentStub = stub
}

func (fake *FakeA2ATaskTracker) GetLatestContextForAgentArgsForCall(i int) string {
	fake.getLatestContextForAgentMutex.RLock()
	defer fake.getLatestContextForAgentMutex.RUnlock()
	argsForCall := fake.getLatestContextForAgentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskTracker) GetLatestContextForAgentReturns(result1 string) {
	fake.getLatestContextForAgentMutex.Lock()
	defer fake.getLatestContextForAgentMutex.Unlock()
	fake.GetLatestContextForAgentStub = nil
	fake.getLatestContextForAgentReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetLatestContextForAgentReturnsOnCall(i int, result1 string) {
	fake.getLatestContextForAgentMutex.Lock()
	defer fake.getLatestContextForAgentMutex.Unlock()
	fake.GetLatestContextForAgentStub = nil
	if fake.getLatestContextForAgentReturnsOnCall == nil {
		fake.getLatestContextForAgentReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getLatestContextForAgentReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetLatestTaskForContext(arg1 string) string {
	fake.getLatestTaskForContextMutex.Lock()
	ret, specificReturn := fake.getLatestTaskForContextReturnsOnCall[len(fake.getLatestTaskForContextArgsForCall)]
	fake.getLatestTaskForContextArgsForCall = append(fake.getLatestTaskForContextArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetLatestTaskForContextStub
	fakeReturns := fake.getLatestTaskForContextReturns
	fake.recordInvocation("GetLatestTaskForContext", []interface{}{arg1})
	fake.getLatestTaskForContextMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskTracker) GetLatestTaskForContextCallCount() int {
	fake.getLatestTaskForContextMutex.RLock()
	defer fake.getLatestTaskForContextMutex.RUnlock()
	return len(fake.getLatestTaskForContextArgsForCall)
}

func (fake *FakeA2ATaskTracker) GetLatestTaskForContextCalls(stub func(string) string) {
	fake.getLatestTaskForContextMutex.Lock()
	defer fake.getLatestTaskForContextMutex.Unlock()
	fake.GetLatestTaskForContextStub = stub
}

func (fake *FakeA2ATaskTracker) GetLatestTaskForContextArgsForCall(i int) string {
	fake.getLatestTaskForContextMutex.RLock()
	defer fake.getLatestTaskForContextMutex.RUnlock()
	argsForCall := fake.getLatestTaskForContextArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskTracker) GetLatestTaskForContextReturns(result1 string) {
	fake.getLatestTaskForContextMutex.Lock()
	defer fake.getLatestTaskForContextMutex.Unlock()
	fake.GetLatestTaskForContextStub = nil
	fake.getLatestTaskForContextReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetLatestTaskForContextReturnsOnCall(i int, result1 string) {
	fake.getLatestTaskForContextMutex.Lock()
	defer fake.getLatestTaskForContextMutex.Unlock()
	fake.GetLatestTaskForContextStub = nil
	if fake.getLatestTaskForContextReturnsOnCall == nil {
		fake.getLatestTaskForContextReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getLatestTaskForContextReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetPollingState(arg1 string) *domain.TaskPollingState {
	fake.getPollingStateMutex.Lock()
	ret, specificReturn := fake.getPollingStateReturnsOnCall[len(fake.getPollingStateArgsForCall)]
	fake.getPollingStateArgsForCall = append(fake.getPollingStateArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetPollingStateStub
	fakeReturns := fake.getPollingStateReturns
	fake.recordInvocation("GetPollingState", []interface{}{arg1})
	fake.getPollingStateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskTracker) GetPollingStateCallCount() int {
	fake.getPollingStateMutex.RLock()
	defer fake.getPollingStateMutex.RUnlock()
	return len(fake.getPollingStateArgsForCall)
}

func (fake *FakeA2ATaskTracker) GetPollingStateCalls(stub func(string) *domain.TaskPollingState) {
	fake.getPollingStateMutex.Lock()
	defer fake.getPollingStateMutex.Unlock()
	fake.GetPollingStateStub = stub
}

func (fake *FakeA2ATaskTracker) GetPollingStateArgsForCall(i int) string {
	fake.getPollingStateMutex.RLock()
	defer fake.getPollingStateMutex.RUnlock()
	argsForCall := fake.getPollingStateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskTracker) GetPollingStateReturns(result1 *domain.TaskPollingState) {
	fake.getPollingStateMutex.Lock()
	defer fake.getPollingStateMutex.Unlock()
	fake.GetPollingStateStub = nil
	fake.getPollingStateReturns = struct {
		result1 *domain.TaskPollingState
	}{result1}
}

func (fake *FakeA2ATaskTracker) GetPollingStateReturnsOnCall(i int, result1 *domain.TaskPollingState) {
	fake.getPollingStateMutex.Lock()
	defer fake.getPollingStateMutex.Unlock()
	fake.GetPollingStateStub = nil
	if fake.getPollingStateReturnsOnCall == nil {
		fake.getPollingStateReturnsOnCall = make(map[int]struct {
			result1 *domain.TaskPollingState
		})
	}
	fake.getPollingStateReturnsOnCall[i] = struct {
		result1 *domain.TaskPollingState
	}{result1}
}

func (fake *FakeA2ATaskTracker) HasContext(arg1 string) bool {
	fake.hasContextMutex.Lock()
	ret, specificReturn := fake.hasContextReturnsOnCall[len(fake.hasContextArgsForCall)]
	fake.hasContextArgsForCall = append(fake.hasContextArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.HasContextStub
	fakeReturns := fake.hasContextReturns
	fake.recordInvocation("HasContext", []interface{}{arg1})
	fake.hasContextMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2ATaskTracker) HasContextCallCount() int {
	fake.hasContextMutex.RLock()
	defer fake.hasContextMutex.RUnlock()
	return len(fake.hasContextArgsForCall)
}

func (fake *FakeA2ATaskTracker) HasContextCalls(stub func(string) bool) {
	fake.hasContextMutex.Lock()
	defer fake.hasContextMutex.Unlock()
	fake.HasContextStub = stub
}

func (fake *FakeA2ATaskTracker) HasContextArgsForCall(i int) string {
	fake.hasContextMutex.RLock()
	defer fake.hasContextMutex.RUnlock()
	argsForCall := fake.hasContextArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskTracker) HasContextReturns(result1 bool) {
	fake.hasContextMutex.Lock()
	defer fake.hasContextMutex.Unlock()
	fake.HasContextStub = nil
	fake.hasContextReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeA2ATaskTracker) HasContextReturnsOnCall(i int, result1 bool) {
	fake.hasContextMutex.Lock()
	defer fake.hasContextMutex.Unlock()
	fake.HasContextStub = nil
	if fake.hasContextReturnsOnCall == nil {
		fake.hasContextReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasContextReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeA2ATaskTracker) RegisterContext(arg1 string, arg2 string) {
	fake.registerContextMutex.Lock()
	fake.registerContextArgsForCall = append(fake.registerContextArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.RegisterContextStub
	fake.recordInvocation("RegisterContext", []interface{}{arg1, arg2})
	fake.registerContextMutex.Unlock()
	if stub != nil {
		fake.RegisterContextStub(arg1, arg2)
	}
}

func (fake *FakeA2ATaskTracker) RegisterContextCallCount() int {
	fake.registerContextMutex.RLock()
	defer fake.registerContextMutex.RUnlock()
	return len(fake.registerContextArgsForCall)
}

func (fake *FakeA2ATaskTracker) RegisterContextCalls(stub func(string, string)) {
	fake.registerContextMutex.Lock()
	defer fake.registerContextMutex.Unlock()
	fake.RegisterContextStub = stub
}

func (fake *FakeA2ATaskTracker) RegisterContextArgsForCall(i int) (string, string) {
	fake.registerContextMutex.RLock()
	defer fake.registerContextMutex.RUnlock()
	argsForCall := fake.registerContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2ATaskTracker) RemoveTask(arg1 string) {
	fake.removeTaskMutex.Lock()
	fake.removeTaskArgsForCall = append(fake.removeTaskArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RemoveTaskStub
	fake.recordInvocation("RemoveTask", []interface{}{arg1})
	fake.removeTaskMutex.Unlock()
	if stub != nil {
		fake.RemoveTaskStub(arg1)
	}
}

func (fake *FakeA2ATaskTracker) RemoveTaskCallCount() int {
	fake.removeTaskMutex.RLock()
	defer fake.removeTaskMutex.RUnlock()
	return len(fake.removeTaskArgsForCall)
}

func (fake *FakeA2ATaskTracker) RemoveTaskCalls(stub func(string)) {
	fake.removeTaskMutex.Lock()
	defer fake.removeTaskMutex.Unlock()
	fake.RemoveTaskStub = stub
}

func (fake *FakeA2ATaskTracker) RemoveTaskArgsForCall(i int) string {
	fake.removeTaskMutex.RLock()
	defer fake.removeTaskMutex.RUnlock()
	argsForCall := fake.removeTaskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskTracker) StartPolling(arg1 string, arg2 *domain.TaskPollingState) {
	fake.startPollingMutex.Lock()
	fake.startPollingArgsForCall = append(fake.startPollingArgsForCall, struct {
		arg1 string
		arg2 *domain.TaskPollingState
	}{arg1, arg2})
	stub := fake.StartPollingStub
	fake.recordInvocation("StartPolling", []interface{}{arg1, arg2})
	fake.startPollingMutex.Unlock()
	if stub != nil {
		fake.StartPollingStub(arg1, arg2)
	}
}

func (fake *FakeA2ATaskTracker) StartPollingCallCount() int {
	fake.startPollingMutex.RLock()
	defer fake.startPollingMutex.RUnlock()
	return len(fake.startPollingArgsForCall)
}

func (fake *FakeA2ATaskTracker) StartPollingCalls(stub func(string, *domain.TaskPollingState)) {
	fake.startPollingMutex.Lock()
	defer fake.startPollingMutex.Unlock()
	fake.StartPollingStub = stub
}

func (fake *FakeA2ATaskTracker) StartPollingArgsForCall(i int) (string, *domain.TaskPollingState) {
	fake.startPollingMutex.RLock()
	defer fake.startPollingMutex.RUnlock()
	argsForCall := fake.startPollingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2ATaskTracker) StopPolling(arg1 string) {
	fake.stopPollingMutex.Lock()
	fake.stopPollingArgsForCall = append(fake.stopPollingArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.StopPollingStub
	fake.recordInvocation("StopPolling", []interface{}{arg1})
	fake.stopPollingMutex.Unlock()
	if stub != nil {
		fake.StopPollingStub(arg1)
	}
}

func (fake *FakeA2ATaskTracker) StopPollingCallCount() int {
	fake.stopPollingMutex.RLock()
	defer fake.stopPollingMutex.RUnlock()
	return len(fake.stopPollingArgsForCall)
}

func (fake *FakeA2ATaskTracker) StopPollingCalls(stub func(string)) {
	fake.stopPollingMutex.Lock()
	defer fake.stopPollingMutex.Unlock()
	fake.StopPollingStub = stub
}

func (fake *FakeA2ATaskTracker) StopPollingArgsForCall(i int) string {
	fake.stopPollingMutex.RLock()
	defer fake.stopPollingMutex.RUnlock()
	argsForCall := fake.stopPollingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2ATaskTracker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeA2ATaskTracker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.A2ATaskTracker = new(FakeA2ATaskTracker)
