// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeSystemReminderProvider struct {
	RemindersDueStub        func(domain.ReminderQuery) []domain.SystemReminder
	remindersDueMutex       sync.RWMutex
	remindersDueArgsForCall []struct {
		arg1 domain.ReminderQuery
	}
	remindersDueReturns struct {
		result1 []domain.SystemReminder
	}
	remindersDueReturnsOnCall map[int]struct {
		result1 []domain.SystemReminder
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSystemReminderProvider) RemindersDue(arg1 domain.ReminderQuery) []domain.SystemReminder {
	fake.remindersDueMutex.Lock()
	ret, specificReturn := fake.remindersDueReturnsOnCall[len(fake.remindersDueArgsForCall)]
	fake.remindersDueArgsForCall = append(fake.remindersDueArgsForCall, struct {
		arg1 domain.ReminderQuery
	}{arg1})
	stub := fake.RemindersDueStub
	fakeReturns := fake.remindersDueReturns
	fake.recordInvocation("RemindersDue", []interface{}{arg1})
	fake.remindersDueMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSystemReminderProvider) RemindersDueCallCount() int {
	fake.remindersDueMutex.RLock()
	defer fake.remindersDueMutex.RUnlock()
	return len(fake.remindersDueArgsForCall)
}

func (fake *FakeSystemReminderProvider) RemindersDueCalls(stub func(domain.ReminderQuery) []domain.SystemReminder) {
	fake.remindersDueMutex.Lock()
	defer fake.remindersDueMutex.Unlock()
	fake.RemindersDueStub = stub
}

func (fake *FakeSystemReminderProvider) RemindersDueArgsForCall(i int) domain.ReminderQuery {
	fake.remindersDueMutex.RLock()
	defer fake.remindersDueMutex.RUnlock()
	argsForCall := fake.remindersDueArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSystemReminderProvider) RemindersDueReturns(result1 []domain.SystemReminder) {
	fake.remindersDueMutex.Lock()
	defer fake.remindersDueMutex.Unlock()
	fake.RemindersDueStub = nil
	fake.remindersDueReturns = struct {
		result1 []domain.SystemReminder
	}{result1}
}

func (fake *FakeSystemReminderProvider) RemindersDueReturnsOnCall(i int, result1 []domain.SystemReminder) {
	fake.remindersDueMutex.Lock()
	defer fake.remindersDueMutex.Unlock()
	fake.RemindersDueStub = nil
	if fake.remindersDueReturnsOnCall == nil {
		fake.remindersDueReturnsOnCall = make(map[int]struct {
			result1 []domain.SystemReminder
		})
	}
	fake.remindersDueReturnsOnCall[i] = struct {
		result1 []domain.SystemReminder
	}{result1}
}

func (fake *FakeSystemReminderProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSystemReminderProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.SystemReminderProvider = new(FakeSystemReminderProvider)
