// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeFrameSource struct {
	GetLatestFrameStub        func() (*domain.Frame, error)
	getLatestFrameMutex       sync.RWMutex
	getLatestFrameArgsForCall []struct {
	}
	getLatestFrameReturns struct {
		result1 *domain.Frame
		result2 error
	}
	getLatestFrameReturnsOnCall map[int]struct {
		result1 *domain.Frame
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFrameSource) GetLatestFrame() (*domain.Frame, error) {
	fake.getLatestFrameMutex.Lock()
	ret, specificReturn := fake.getLatestFrameReturnsOnCall[len(fake.getLatestFrameArgsForCall)]
	fake.getLatestFrameArgsForCall = append(fake.getLatestFrameArgsForCall, struct {
	}{})
	stub := fake.GetLatestFrameStub
	fakeReturns := fake.getLatestFrameReturns
	fake.recordInvocation("GetLatestFrame", []interface{}{})
	fake.getLatestFrameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFrameSource) GetLatestFrameCallCount() int {
	fake.getLatestFrameMutex.RLock()
	defer fake.getLatestFrameMutex.RUnlock()
	return len(fake.getLatestFrameArgsForCall)
}

func (fake *FakeFrameSource) GetLatestFrameCalls(stub func() (*domain.Frame, error)) {
	fake.getLatestFrameMutex.Lock()
	defer fake.getLatestFrameMutex.Unlock()
	fake.GetLatestFrameStub = stub
}

func (fake *FakeFrameSource) GetLatestFrameReturns(result1 *domain.Frame, result2 error) {
	fake.getLatestFrameMutex.Lock()
	defer fake.getLatestFrameMutex.Unlock()
	fake.GetLatestFrameStub = nil
	fake.getLatestFrameReturns = struct {
		result1 *domain.Frame
		result2 error
	}{result1, result2}
}

func (fake *FakeFrameSource) GetLatestFrameReturnsOnCall(i int, result1 *domain.Frame, result2 error) {
	fake.getLatestFrameMutex.Lock()
	defer fake.getLatestFrameMutex.Unlock()
	fake.GetLatestFrameStub = nil
	if fake.getLatestFrameReturnsOnCall == nil {
		fake.getLatestFrameReturnsOnCall = make(map[int]struct {
			result1 *domain.Frame
			result2 error
		})
	}
	fake.getLatestFrameReturnsOnCall[i] = struct {
		result1 *domain.Frame
		result2 error
	}{result1, result2}
}

func (fake *FakeFrameSource) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFrameSource) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.FrameSource = new(FakeFrameSource)
