// Code generated by counterfeiter. DO NOT EDIT.
package domain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain"
)

type FakeJobLivenessReporter struct {
	IsJobRunningStub        func(string) bool
	isJobRunningMutex       sync.RWMutex
	isJobRunningArgsForCall []struct {
		arg1 string
	}
	isJobRunningReturns struct {
		result1 bool
	}
	isJobRunningReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobLivenessReporter) IsJobRunning(arg1 string) bool {
	fake.isJobRunningMutex.Lock()
	ret, specificReturn := fake.isJobRunningReturnsOnCall[len(fake.isJobRunningArgsForCall)]
	fake.isJobRunningArgsForCall = append(fake.isJobRunningArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsJobRunningStub
	fakeReturns := fake.isJobRunningReturns
	fake.recordInvocation("IsJobRunning", []interface{}{arg1})
	fake.isJobRunningMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobLivenessReporter) IsJobRunningCallCount() int {
	fake.isJobRunningMutex.RLock()
	defer fake.isJobRunningMutex.RUnlock()
	return len(fake.isJobRunningArgsForCall)
}

func (fake *FakeJobLivenessReporter) IsJobRunningCalls(stub func(string) bool) {
	fake.isJobRunningMutex.Lock()
	defer fake.isJobRunningMutex.Unlock()
	fake.IsJobRunningStub = stub
}

func (fake *FakeJobLivenessReporter) IsJobRunningArgsForCall(i int) string {
	fake.isJobRunningMutex.RLock()
	defer fake.isJobRunningMutex.RUnlock()
	argsForCall := fake.isJobRunningArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeJobLivenessReporter) IsJobRunningReturns(result1 bool) {
	fake.isJobRunningMutex.Lock()
	defer fake.isJobRunningMutex.Unlock()
	fake.IsJobRunningStub = nil
	fake.isJobRunningReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeJobLivenessReporter) IsJobRunningReturnsOnCall(i int, result1 bool) {
	fake.isJobRunningMutex.Lock()
	defer fake.isJobRunningMutex.Unlock()
	fake.IsJobRunningStub = nil
	if fake.isJobRunningReturnsOnCall == nil {
		fake.isJobRunningReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isJobRunningReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeJobLivenessReporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobLivenessReporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.JobLivenessReporter = new(FakeJobLivenessReporter)
