// Code generated by counterfeiter. DO NOT EDIT.
package agui

import (
	"sync"

	"github.com/inference-gateway/cli/internal/protocols/agui"
)

type FakeHandler struct {
	AttachStub        func(*agui.Conn)
	attachMutex       sync.RWMutex
	attachArgsForCall []struct {
		arg1 *agui.Conn
	}
	DetachStub        func(*agui.Conn)
	detachMutex       sync.RWMutex
	detachArgsForCall []struct {
		arg1 *agui.Conn
	}
	HandleStub        func(*agui.Conn, []byte)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 *agui.Conn
		arg2 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHandler) Attach(arg1 *agui.Conn) {
	fake.attachMutex.Lock()
	fake.attachArgsForCall = append(fake.attachArgsForCall, struct {
		arg1 *agui.Conn
	}{arg1})
	stub := fake.AttachStub
	fake.recordInvocation("Attach", []interface{}{arg1})
	fake.attachMutex.Unlock()
	if stub != nil {
		fake.AttachStub(arg1)
	}
}

func (fake *FakeHandler) AttachCallCount() int {
	fake.attachMutex.RLock()
	defer fake.attachMutex.RUnlock()
	return len(fake.attachArgsForCall)
}

func (fake *FakeHandler) AttachCalls(stub func(*agui.Conn)) {
	fake.attachMutex.Lock()
	defer fake.attachMutex.Unlock()
	fake.AttachStub = stub
}

func (fake *FakeHandler) AttachArgsForCall(i int) *agui.Conn {
	fake.attachMutex.RLock()
	defer fake.attachMutex.RUnlock()
	argsForCall := fake.attachArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHandler) Detach(arg1 *agui.Conn) {
	fake.detachMutex.Lock()
	fake.detachArgsForCall = append(fake.detachArgsForCall, struct {
		arg1 *agui.Conn
	}{arg1})
	stub := fake.DetachStub
	fake.recordInvocation("Detach", []interface{}{arg1})
	fake.detachMutex.Unlock()
	if stub != nil {
		fake.DetachStub(arg1)
	}
}

func (fake *FakeHandler) DetachCallCount() int {
	fake.detachMutex.RLock()
	defer fake.detachMutex.RUnlock()
	return len(fake.detachArgsForCall)
}

func (fake *FakeHandler) DetachCalls(stub func(*agui.Conn)) {
	fake.detachMutex.Lock()
	defer fake.detachMutex.Unlock()
	fake.DetachStub = stub
}

func (fake *FakeHandler) DetachArgsForCall(i int) *agui.Conn {
	fake.detachMutex.RLock()
	defer fake.detachMutex.RUnlock()
	argsForCall := fake.detachArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHandler) Handle(arg1 *agui.Conn, arg2 []byte) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.handleMutex.Lock()
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 *agui.Conn
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.HandleStub
	fake.recordInvocation("Handle", []interface{}{arg1, arg2Copy})
	fake.handleMutex.Unlock()
	if stub != nil {
		fake.HandleStub(arg1, arg2)
	}
}

func (fake *FakeHandler) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeHandler) HandleCalls(stub func(*agui.Conn, []byte)) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakeHandler) HandleArgsForCall(i int) (*agui.Conn, []byte) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agui.Handler = new(FakeHandler)
