// Code generated by counterfeiter. DO NOT EDIT.
package storage

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/platform/storage"
)

type FakeShellHistoryStorage struct {
	AppendHistoryStub        func(context.Context, string) error
	appendHistoryMutex       sync.RWMutex
	appendHistoryArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	appendHistoryReturns struct {
		result1 error
	}
	appendHistoryReturnsOnCall map[int]struct {
		result1 error
	}
	LoadHistoryStub        func(context.Context, int) ([]string, error)
	loadHistoryMutex       sync.RWMutex
	loadHistoryArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	loadHistoryReturns struct {
		result1 []string
		result2 error
	}
	loadHistoryReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeShellHistoryStorage) AppendHistory(arg1 context.Context, arg2 string) error {
	fake.appendHistoryMutex.Lock()
	ret, specificReturn := fake.appendHistoryReturnsOnCall[len(fake.appendHistoryArgsForCall)]
	fake.appendHistoryArgsForCall = append(fake.appendHistoryArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.AppendHistoryStub
	fakeReturns := fake.appendHistoryReturns
	fake.recordInvocation("AppendHistory", []interface{}{arg1, arg2})
	fake.appendHistoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeShellHistoryStorage) AppendHistoryCallCount() int {
	fake.appendHistoryMutex.RLock()
	defer fake.appendHistoryMutex.RUnlock()
	return len(fake.appendHistoryArgsForCall)
}

func (fake *FakeShellHistoryStorage) AppendHistoryCalls(stub func(context.Context, string) error) {
	fake.appendHistoryMutex.Lock()
	defer fake.appendHistoryMutex.Unlock()
	fake.AppendHistoryStub = stub
}

func (fake *FakeShellHistoryStorage) AppendHistoryArgsForCall(i int) (context.Context, string) {
	fake.appendHistoryMutex.RLock()
	defer fake.appendHistoryMutex.RUnlock()
	argsForCall := fake.appendHistoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeShellHistoryStorage) AppendHistoryReturns(result1 error) {
	fake.appendHistoryMutex.Lock()
	defer fake.appendHistoryMutex.Unlock()
	fake.AppendHistoryStub = nil
	fake.appendHistoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeShellHistoryStorage) AppendHistoryReturnsOnCall(i int, result1 error) {
	fake.appendHistoryMutex.Lock()
	defer fake.appendHistoryMutex.Unlock()
	fake.AppendHistoryStub = nil
	if fake.appendHistoryReturnsOnCall == nil {
		fake.appendHistoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.appendHistoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeShellHistoryStorage) LoadHistory(arg1 context.Context, arg2 int) ([]string, error) {
	fake.loadHistoryMutex.Lock()
	ret, specificReturn := fake.loadHistoryReturnsOnCall[len(fake.loadHistoryArgsForCall)]
	fake.loadHistoryArgsForCall = append(fake.loadHistoryArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.LoadHistoryStub
	fakeReturns := fake.loadHistoryReturns
	fake.recordInvocation("LoadHistory", []interface{}{arg1, arg2})
	fake.loadHistoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeShellHistoryStorage) LoadHistoryCallCount() int {
	fake.loadHistoryMutex.RLock()
	defer fake.loadHistoryMutex.RUnlock()
	return len(fake.loadHistoryArgsForCall)
}

func (fake *FakeShellHistoryStorage) LoadHistoryCalls(stub func(context.Context, int) ([]string, error)) {
	fake.loadHistoryMutex.Lock()
	defer fake.loadHistoryMutex.Unlock()
	fake.LoadHistoryStub = stub
}

func (fake *FakeShellHistoryStorage) LoadHistoryArgsForCall(i int) (context.Context, int) {
	fake.loadHistoryMutex.RLock()
	defer fake.loadHistoryMutex.RUnlock()
	argsForCall := fake.loadHistoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeShellHistoryStorage) LoadHistoryReturns(result1 []string, result2 error) {
	fake.loadHistoryMutex.Lock()
	defer fake.loadHistoryMutex.Unlock()
	fake.LoadHistoryStub = nil
	fake.loadHistoryReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeShellHistoryStorage) LoadHistoryReturnsOnCall(i int, result1 []string, result2 error) {
	fake.loadHistoryMutex.Lock()
	defer fake.loadHistoryMutex.Unlock()
	fake.LoadHistoryStub = nil
	if fake.loadHistoryReturnsOnCall == nil {
		fake.loadHistoryReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.loadHistoryReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeShellHistoryStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeShellHistoryStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.ShellHistoryStorage = new(FakeShellHistoryStorage)
