// Code generated by counterfeiter. DO NOT EDIT.
package filewriter

import (
	"sync"

	"github.com/inference-gateway/cli/internal/domain/filewriter"
)

type FakePathValidator struct {
	IsInSandboxStub        func(string) bool
	isInSandboxMutex       sync.RWMutex
	isInSandboxArgsForCall []struct {
		arg1 string
	}
	isInSandboxReturns struct {
		result1 bool
	}
	isInSandboxReturnsOnCall map[int]struct {
		result1 bool
	}
	IsWritableStub        func(string) bool
	isWritableMutex       sync.RWMutex
	isWritableArgsForCall []struct {
		arg1 string
	}
	isWritableReturns struct {
		result1 bool
	}
	isWritableReturnsOnCall map[int]struct {
		result1 bool
	}
	ValidateStub        func(string) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 string
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePathValidator) IsInSandbox(arg1 string) bool {
	fake.isInSandboxMutex.Lock()
	ret, specificReturn := fake.isInSandboxReturnsOnCall[len(fake.isInSandboxArgsForCall)]
	fake.isInSandboxArgsForCall = append(fake.isInSandboxArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsInSandboxStub
	fakeReturns := fake.isInSandboxReturns
	fake.recordInvocation("IsInSandbox", []interface{}{arg1})
	fake.isInSandboxMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePathValidator) IsInSandboxCallCount() int {
	fake.isInSandboxMutex.RLock()
	defer fake.isInSandboxMutex.RUnlock()
	return len(fake.isInSandboxArgsForCall)
}

func (fake *FakePathValidator) IsInSandboxCalls(stub func(string) bool) {
	fake.isInSandboxMutex.Lock()
	defer fake.isInSandboxMutex.Unlock()
	fake.IsInSandboxStub = stub
}

func (fake *FakePathValidator) IsInSandboxArgsForCall(i int) string {
	fake.isInSandboxMutex.RLock()
	defer fake.isInSandboxMutex.RUnlock()
	argsForCall := fake.isInSandboxArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePathValidator) IsInSandboxReturns(result1 bool) {
	fake.isInSandboxMutex.Lock()
	defer fake.isInSandboxMutex.Unlock()
	fake.IsInSandboxStub = nil
	fake.isInSandboxReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakePathValidator) IsInSandboxReturnsOnCall(i int, result1 bool) {
	fake.isInSandboxMutex.Lock()
	defer fake.isInSandboxMutex.Unlock()
	fake.IsInSandboxStub = nil
	if fake.isInSandboxReturnsOnCall == nil {
		fake.isInSandboxReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isInSandboxReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakePathValidator) IsWritable(arg1 string) bool {
	fake.isWritableMutex.Lock()
	ret, specificReturn := fake.isWritableReturnsOnCall[len(fake.isWritableArgsForCall)]
	fake.isWritableArgsForCall = append(fake.isWritableArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsWritableStub
	fakeReturns := fake.isWritableReturns
	fake.recordInvocation("IsWritable", []interface{}{arg1})
	fake.isWritableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePathValidator) IsWritableCallCount() int {
	fake.isWritableMutex.RLock()
	defer fake.isWritableMutex.RUnlock()
	return len(fake.isWritableArgsForCall)
}

func (fake *FakePathValidator) IsWritableCalls(stub func(string) bool) {
	fake.isWritableMutex.Lock()
	defer fake.isWritableMutex.Unlock()
	fake.IsWritableStub = stub
}

func (fake *FakePathValidator) IsWritableArgsForCall(i int) string {
	fake.isWritableMutex.RLock()
	defer fake.isWritableMutex.RUnlock()
	argsForCall := fake.isWritableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePathValidator) IsWritableReturns(result1 bool) {
	fake.isWritableMutex.Lock()
	defer fake.isWritableMutex.Unlock()
	fake.IsWritableStub = nil
	fake.isWritableReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakePathValidator) IsWritableReturnsOnCall(i int, result1 bool) {
	fake.isWritableMutex.Lock()
	defer fake.isWritableMutex.Unlock()
	fake.IsWritableStub = nil
	if fake.isWritableReturnsOnCall == nil {
		fake.isWritableReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isWritableReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakePathValidator) Validate(arg1 string) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePathValidator) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakePathValidator) ValidateCalls(stub func(string) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakePathValidator) ValidateArgsForCall(i int) string {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePathValidator) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePathValidator) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePathValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePathValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ filewriter.PathValidator = new(FakePathValidator)
