// Code generated by counterfeiter. DO NOT EDIT.
package states

import (
	"sync"

	"github.com/inference-gateway/cli/internal/agent/states"
)

type FakeStateHandler struct {
	HandleStub        func(states.AgentEvent) error
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 states.AgentEvent
	}
	handleReturns struct {
		result1 error
	}
	handleReturnsOnCall map[int]struct {
		result1 error
	}
	NameStub        func() states.AgentExecutionState
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 states.AgentExecutionState
	}
	nameReturnsOnCall map[int]struct {
		result1 states.AgentExecutionState
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStateHandler) Handle(arg1 states.AgentEvent) error {
	fake.handleMutex.Lock()
	ret, specificReturn := fake.handleReturnsOnCall[len(fake.handleArgsForCall)]
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 states.AgentEvent
	}{arg1})
	stub := fake.HandleStub
	fakeReturns := fake.handleReturns
	fake.recordInvocation("Handle", []interface{}{arg1})
	fake.handleMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStateHandler) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeStateHandler) HandleCalls(stub func(states.AgentEvent) error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakeStateHandler) HandleArgsForCall(i int) states.AgentEvent {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStateHandler) HandleReturns(result1 error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = nil
	fake.handleReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStateHandler) HandleReturnsOnCall(i int, result1 error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = nil
	if fake.handleReturnsOnCall == nil {
		fake.handleReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.handleReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStateHandler) Name() states.AgentExecutionState {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStateHandler) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeStateHandler) NameCalls(stub func() states.AgentExecutionState) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeStateHandler) NameReturns(result1 states.AgentExecutionState) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 states.AgentExecutionState
	}{result1}
}

func (fake *FakeStateHandler) NameReturnsOnCall(i int, result1 states.AgentExecutionState) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 states.AgentExecutionState
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 states.AgentExecutionState
	}{result1}
}

func (fake *FakeStateHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStateHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ states.StateHandler = new(FakeStateHandler)
