package config

// PricingConfig holds configuration for model pricing and cost tracking.
type PricingConfig struct {
	Enabled      bool                     `yaml:"enabled" mapstructure:"enabled"`
	Currency     string                   `yaml:"currency" mapstructure:"currency"`
	CustomPrices map[string]CustomPricing `yaml:"custom_prices" mapstructure:"custom_prices"`
}

// CustomPricing allows users to override default pricing for specific models.
type CustomPricing struct {
	InputPricePerMToken  float64 `yaml:"input_price_per_mtoken" mapstructure:"input_price_per_mtoken"`
	OutputPricePerMToken float64 `yaml:"output_price_per_mtoken" mapstructure:"output_price_per_mtoken"`
}

// ModelPricing represents pricing information for a specific model.
// Prices are per million tokens to align with common pricing conventions.
type ModelPricing struct {
	Provider             string
	Model                string
	InputPricePerMToken  float64
	OutputPricePerMToken float64
	Currency             string
}

// GetDefaultPricingConfig returns the default pricing configuration.
func GetDefaultPricingConfig() PricingConfig {
	return PricingConfig{
		Enabled:      true,
		Currency:     "USD",
		CustomPrices: make(map[string]CustomPricing),
	}
}

// DefaultModelPricing contains hardcoded pricing for common models.
// Prices are based on publicly available pricing as of December 2024.
// Users can override these in their config files.
var DefaultModelPricing = map[string]ModelPricing{
	"anthropic/claude-opus-4-7": {
		Provider:             "anthropic",
		Model:                "claude-opus-4-7",
		InputPricePerMToken:  5.00,
		OutputPricePerMToken: 25.00,
		Currency:             "USD",
	},
	"anthropic/claude-sonnet-4-6": {
		Provider:             "anthropic",
		Model:                "claude-sonnet-4-6",
		InputPricePerMToken:  3.00,
		OutputPricePerMToken: 15.00,
		Currency:             "USD",
	},
	"anthropic/claude-opus-4-6": {
		Provider:             "anthropic",
		Model:                "claude-opus-4-6",
		InputPricePerMToken:  5.00,
		OutputPricePerMToken: 25.00,
		Currency:             "USD",
	},
	"anthropic/claude-opus-4-5-20251101": {
		Provider:             "anthropic",
		Model:                "claude-opus-4-5-20251101",
		InputPricePerMToken:  5.00,
		OutputPricePerMToken: 25.00,
		Currency:             "USD",
	},
	"anthropic/claude-haiku-4-5-20251001": {
		Provider:             "anthropic",
		Model:                "claude-haiku-4-5-20251001",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 5.00,
		Currency:             "USD",
	},
	"anthropic/claude-sonnet-4-5-20250929": {
		Provider:             "anthropic",
		Model:                "claude-sonnet-4-5-20250929",
		InputPricePerMToken:  3.00,
		OutputPricePerMToken: 15.00,
		Currency:             "USD",
	},
	"anthropic/claude-opus-4-1-20250805": {
		Provider:             "anthropic",
		Model:                "claude-opus-4-1-20250805",
		InputPricePerMToken:  15.00,
		OutputPricePerMToken: 75.00,
		Currency:             "USD",
	},
	"anthropic/claude-opus-4-20250514": {
		Provider:             "anthropic",
		Model:                "claude-opus-4-20250514",
		InputPricePerMToken:  15.00,
		OutputPricePerMToken: 75.00,
		Currency:             "USD",
	},
	"anthropic/claude-sonnet-4-20250514": {
		Provider:             "anthropic",
		Model:                "claude-sonnet-4-20250514",
		InputPricePerMToken:  3.00,
		OutputPricePerMToken: 15.00,
		Currency:             "USD",
	},
	"openai/gpt-4o": {
		Provider:             "openai",
		Model:                "gpt-4o",
		InputPricePerMToken:  2.50,
		OutputPricePerMToken: 10.00,
		Currency:             "USD",
	},
	"openai/gpt-4o-mini": {
		Provider:             "openai",
		Model:                "gpt-4o-mini",
		InputPricePerMToken:  0.150,
		OutputPricePerMToken: 0.600,
		Currency:             "USD",
	},
	"openai/gpt-4-turbo": {
		Provider:             "openai",
		Model:                "gpt-4-turbo",
		InputPricePerMToken:  10.00,
		OutputPricePerMToken: 30.00,
		Currency:             "USD",
	},
	"openai/gpt-4": {
		Provider:             "openai",
		Model:                "gpt-4",
		InputPricePerMToken:  30.00,
		OutputPricePerMToken: 60.00,
		Currency:             "USD",
	},
	"openai/gpt-3.5-turbo": {
		Provider:             "openai",
		Model:                "gpt-3.5-turbo",
		InputPricePerMToken:  0.50,
		OutputPricePerMToken: 1.50,
		Currency:             "USD",
	},
	"openai/o1": {
		Provider:             "openai",
		Model:                "o1",
		InputPricePerMToken:  15.00,
		OutputPricePerMToken: 60.00,
		Currency:             "USD",
	},
	"openai/o1-mini": {
		Provider:             "openai",
		Model:                "o1-mini",
		InputPricePerMToken:  3.00,
		OutputPricePerMToken: 12.00,
		Currency:             "USD",
	},
	"openai/o1-preview": {
		Provider:             "openai",
		Model:                "o1-preview",
		InputPricePerMToken:  15.00,
		OutputPricePerMToken: 60.00,
		Currency:             "USD",
	},
	"google/models/gemini-2.5-pro": {
		Provider:             "google",
		Model:                "models/gemini-2.5-pro",
		InputPricePerMToken:  1.25,
		OutputPricePerMToken: 10.00,
		Currency:             "USD",
	},
	"google/models/gemini-2.5-flash": {
		Provider:             "google",
		Model:                "models/gemini-2.5-flash",
		InputPricePerMToken:  0.30,
		OutputPricePerMToken: 2.50,
		Currency:             "USD",
	},
	"google/models/gemini-2.5-flash-lite": {
		Provider:             "google",
		Model:                "models/gemini-2.5-flash-lite",
		InputPricePerMToken:  0.10,
		OutputPricePerMToken: 0.40,
		Currency:             "USD",
	},
	"google/models/gemini-2.0-flash": {
		Provider:             "google",
		Model:                "models/gemini-2.0-flash",
		InputPricePerMToken:  0.10,
		OutputPricePerMToken: 0.40,
		Currency:             "USD",
	},
	"google/models/gemini-2.0-flash-001": {
		Provider:             "google",
		Model:                "models/gemini-2.0-flash-001",
		InputPricePerMToken:  0.10,
		OutputPricePerMToken: 0.40,
		Currency:             "USD",
	},
	"google/models/gemini-2.0-flash-lite": {
		Provider:             "google",
		Model:                "models/gemini-2.0-flash-lite",
		InputPricePerMToken:  0.075,
		OutputPricePerMToken: 0.30,
		Currency:             "USD",
	},
	"google/models/gemini-2.0-flash-lite-001": {
		Provider:             "google",
		Model:                "models/gemini-2.0-flash-lite-001",
		InputPricePerMToken:  0.075,
		OutputPricePerMToken: 0.30,
		Currency:             "USD",
	},
	"google/models/gemini-2.5-flash-preview-tts": {
		Provider:             "google",
		Model:                "models/gemini-2.5-flash-preview-tts",
		InputPricePerMToken:  0.50,
		OutputPricePerMToken: 10.00,
		Currency:             "USD",
	},
	"google/models/gemini-2.5-pro-preview-tts": {
		Provider:             "google",
		Model:                "models/gemini-2.5-pro-preview-tts",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 20.00,
		Currency:             "USD",
	},
	"google/models/gemini-3-flash-preview": {
		Provider:             "google",
		Model:                "models/gemini-3-flash-preview",
		InputPricePerMToken:  0.50,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
	"google/models/gemini-3.1-pro-preview": {
		Provider:             "google",
		Model:                "models/gemini-3.1-pro-preview",
		InputPricePerMToken:  2.00,
		OutputPricePerMToken: 12.00,
		Currency:             "USD",
	},
	"google/models/gemini-3.1-flash-lite-preview": {
		Provider:             "google",
		Model:                "models/gemini-3.1-flash-lite-preview",
		InputPricePerMToken:  0.25,
		OutputPricePerMToken: 1.50,
		Currency:             "USD",
	},
	"google/models/gemini-embedding-001": {
		Provider:             "google",
		Model:                "models/gemini-embedding-001",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemini-embedding-2": {
		Provider:             "google",
		Model:                "models/gemini-embedding-2",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-3-1b-it": {
		Provider:             "google",
		Model:                "models/gemma-3-1b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-3-4b-it": {
		Provider:             "google",
		Model:                "models/gemma-3-4b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-3-12b-it": {
		Provider:             "google",
		Model:                "models/gemma-3-12b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-3-27b-it": {
		Provider:             "google",
		Model:                "models/gemma-3-27b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-3n-e2b-it": {
		Provider:             "google",
		Model:                "models/gemma-3n-e2b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-3n-e4b-it": {
		Provider:             "google",
		Model:                "models/gemma-3n-e4b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-4-26b-a4b-it": {
		Provider:             "google",
		Model:                "models/gemma-4-26b-a4b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/models/gemma-4-31b-it": {
		Provider:             "google",
		Model:                "models/gemma-4-31b-it",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"google/gemini-1.5-pro": {
		Provider:             "google",
		Model:                "gemini-1.5-pro",
		InputPricePerMToken:  1.25,
		OutputPricePerMToken: 5.00,
		Currency:             "USD",
	},
	"google/gemini-1.5-flash": {
		Provider:             "google",
		Model:                "gemini-1.5-flash",
		InputPricePerMToken:  0.075,
		OutputPricePerMToken: 0.30,
		Currency:             "USD",
	},
	"google/gemini-pro": {
		Provider:             "google",
		Model:                "gemini-pro",
		InputPricePerMToken:  0.50,
		OutputPricePerMToken: 1.50,
		Currency:             "USD",
	},
	"deepseek/deepseek-v4-pro": {
		Provider:             "deepseek",
		Model:                "deepseek-v4-pro",
		InputPricePerMToken:  1.74,
		OutputPricePerMToken: 3.48,
		Currency:             "USD",
	},
	"deepseek/deepseek-v4-flash": {
		Provider:             "deepseek",
		Model:                "deepseek-v4-flash",
		InputPricePerMToken:  0.14,
		OutputPricePerMToken: 0.28,
		Currency:             "USD",
	},
	"ollama_cloud/kimi-k2.5": {
		Provider:             "ollama_cloud",
		Model:                "kimi-k2.5",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/kimi-k2.6": {
		Provider:             "ollama_cloud",
		Model:                "kimi-k2.6",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/qwen3-coder:480b": {
		Provider:             "ollama_cloud",
		Model:                "qwen3-coder:480b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/qwen3-coder-next": {
		Provider:             "ollama_cloud",
		Model:                "qwen3-coder-next",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/qwen3-vl:235b": {
		Provider:             "ollama_cloud",
		Model:                "qwen3-vl:235b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/qwen3-vl:235b-instruct": {
		Provider:             "ollama_cloud",
		Model:                "qwen3-vl:235b-instruct",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/qwen3-next:80b": {
		Provider:             "ollama_cloud",
		Model:                "qwen3-next:80b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/qwen3.5:397b": {
		Provider:             "ollama_cloud",
		Model:                "qwen3.5:397b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/devstral-2:123b": {
		Provider:             "ollama_cloud",
		Model:                "devstral-2:123b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/devstral-small-2:24b": {
		Provider:             "ollama_cloud",
		Model:                "devstral-small-2:24b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gemma3:4b": {
		Provider:             "ollama_cloud",
		Model:                "gemma3:4b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gemma3:12b": {
		Provider:             "ollama_cloud",
		Model:                "gemma3:12b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gemma3:27b": {
		Provider:             "ollama_cloud",
		Model:                "gemma3:27b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gemma4:31b": {
		Provider:             "ollama_cloud",
		Model:                "gemma4:31b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/ministral-3:3b": {
		Provider:             "ollama_cloud",
		Model:                "ministral-3:3b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/ministral-3:8b": {
		Provider:             "ollama_cloud",
		Model:                "ministral-3:8b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/ministral-3:14b": {
		Provider:             "ollama_cloud",
		Model:                "ministral-3:14b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/mistral-large-3:675b": {
		Provider:             "ollama_cloud",
		Model:                "mistral-large-3:675b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/glm-4.6": {
		Provider:             "ollama_cloud",
		Model:                "glm-4.6",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/glm-4.7": {
		Provider:             "ollama_cloud",
		Model:                "glm-4.7",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/glm-5": {
		Provider:             "ollama_cloud",
		Model:                "glm-5",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/glm-5.1": {
		Provider:             "ollama_cloud",
		Model:                "glm-5.1",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gpt-oss:20b": {
		Provider:             "ollama_cloud",
		Model:                "gpt-oss:20b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gpt-oss:120b": {
		Provider:             "ollama_cloud",
		Model:                "gpt-oss:120b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/minimax-m2": {
		Provider:             "ollama_cloud",
		Model:                "minimax-m2",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/minimax-m2.1": {
		Provider:             "ollama_cloud",
		Model:                "minimax-m2.1",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/minimax-m2.5": {
		Provider:             "ollama_cloud",
		Model:                "minimax-m2.5",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/minimax-m2.7": {
		Provider:             "ollama_cloud",
		Model:                "minimax-m2.7",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/nemotron-3-nano:30b": {
		Provider:             "ollama_cloud",
		Model:                "nemotron-3-nano:30b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/nemotron-3-super": {
		Provider:             "ollama_cloud",
		Model:                "nemotron-3-super",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/deepseek-v3.2": {
		Provider:             "ollama_cloud",
		Model:                "deepseek-v3.2",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/deepseek-v4-flash": {
		Provider:             "ollama_cloud",
		Model:                "deepseek-v4-flash",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/deepseek-v4-pro": {
		Provider:             "ollama_cloud",
		Model:                "deepseek-v4-pro",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/gemini-3-flash-preview": {
		Provider:             "ollama_cloud",
		Model:                "gemini-3-flash-preview",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"ollama_cloud/rnj-1:8b": {
		Provider:             "ollama_cloud",
		Model:                "rnj-1:8b",
		InputPricePerMToken:  0.00,
		OutputPricePerMToken: 0.00,
		Currency:             "USD",
	},
	"moonshot/kimi-k2.5": {
		Provider:             "moonshot",
		Model:                "kimi-k2.5",
		InputPricePerMToken:  0.60,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
	"moonshot/kimi-k2.6": {
		Provider:             "moonshot",
		Model:                "kimi-k2.6",
		InputPricePerMToken:  0.74,
		OutputPricePerMToken: 4.66,
		Currency:             "USD",
	},
	"groq/llama-3.3-70b-versatile": {
		Provider:             "groq",
		Model:                "llama-3.3-70b-versatile",
		InputPricePerMToken:  0.59,
		OutputPricePerMToken: 0.79,
		Currency:             "USD",
	},
	"groq/llama-3.1-8b-instant": {
		Provider:             "groq",
		Model:                "llama-3.1-8b-instant",
		InputPricePerMToken:  0.05,
		OutputPricePerMToken: 0.08,
		Currency:             "USD",
	},
	"groq/meta-llama/llama-4-scout-17b-16e-instruct": {
		Provider:             "groq",
		Model:                "meta-llama/llama-4-scout-17b-16e-instruct",
		InputPricePerMToken:  0.11,
		OutputPricePerMToken: 0.34,
		Currency:             "USD",
	},
	"groq/meta-llama/llama-4-maverick-17b-128e-instruct": {
		Provider:             "groq",
		Model:                "meta-llama/llama-4-maverick-17b-128e-instruct",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 0.60,
		Currency:             "USD",
	},
	"groq/meta-llama/llama-guard-4-12b": {
		Provider:             "groq",
		Model:                "meta-llama/llama-guard-4-12b",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 0.20,
		Currency:             "USD",
	},
	"groq/qwen/qwen3-32b": {
		Provider:             "groq",
		Model:                "qwen/qwen3-32b",
		InputPricePerMToken:  0.29,
		OutputPricePerMToken: 0.59,
		Currency:             "USD",
	},
	"groq/openai/gpt-oss-20b": {
		Provider:             "groq",
		Model:                "openai/gpt-oss-20b",
		InputPricePerMToken:  0.075,
		OutputPricePerMToken: 0.30,
		Currency:             "USD",
	},
	"groq/openai/gpt-oss-safeguard-20b": {
		Provider:             "groq",
		Model:                "openai/gpt-oss-safeguard-20b",
		InputPricePerMToken:  0.075,
		OutputPricePerMToken: 0.30,
		Currency:             "USD",
	},
	"groq/openai/gpt-oss-120b": {
		Provider:             "groq",
		Model:                "openai/gpt-oss-120b",
		InputPricePerMToken:  0.15,
		OutputPricePerMToken: 0.60,
		Currency:             "USD",
	},
	"groq/moonshotai/kimi-k2-instruct-0905": {
		Provider:             "groq",
		Model:                "moonshotai/kimi-k2-instruct-0905",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
	"mistral/mistral-large": {
		Provider:             "mistral",
		Model:                "mistral-large",
		InputPricePerMToken:  2.00,
		OutputPricePerMToken: 6.00,
		Currency:             "USD",
	},
	"mistral/mistral-medium": {
		Provider:             "mistral",
		Model:                "mistral-medium",
		InputPricePerMToken:  2.70,
		OutputPricePerMToken: 8.10,
		Currency:             "USD",
	},
	"mistral/mistral-small": {
		Provider:             "mistral",
		Model:                "mistral-small",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 0.60,
		Currency:             "USD",
	},
	"mistral/mistral-7b": {
		Provider:             "mistral",
		Model:                "mistral-7b",
		InputPricePerMToken:  0.25,
		OutputPricePerMToken: 0.25,
		Currency:             "USD",
	},
	"mistral/mixtral-8x7b": {
		Provider:             "mistral",
		Model:                "mixtral-8x7b",
		InputPricePerMToken:  0.70,
		OutputPricePerMToken: 0.70,
		Currency:             "USD",
	},
	"cohere/command-r-plus": {
		Provider:             "cohere",
		Model:                "command-r-plus",
		InputPricePerMToken:  2.50,
		OutputPricePerMToken: 10.00,
		Currency:             "USD",
	},
	"cohere/command-r": {
		Provider:             "cohere",
		Model:                "command-r",
		InputPricePerMToken:  0.50,
		OutputPricePerMToken: 1.50,
		Currency:             "USD",
	},
	"cohere/command": {
		Provider:             "cohere",
		Model:                "command",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 2.00,
		Currency:             "USD",
	},
	"cohere/command-light": {
		Provider:             "cohere",
		Model:                "command-light",
		InputPricePerMToken:  0.30,
		OutputPricePerMToken: 0.60,
		Currency:             "USD",
	},
	"ollama/llama3.2": {
		Provider:             "ollama",
		Model:                "llama3.2",
		InputPricePerMToken:  0.0,
		OutputPricePerMToken: 0.0,
		Currency:             "USD",
	},
	"ollama/llama3.1": {
		Provider:             "ollama",
		Model:                "llama3.1",
		InputPricePerMToken:  0.0,
		OutputPricePerMToken: 0.0,
		Currency:             "USD",
	},
	"ollama/codellama": {
		Provider:             "ollama",
		Model:                "codellama",
		InputPricePerMToken:  0.0,
		OutputPricePerMToken: 0.0,
		Currency:             "USD",
	},
	"ollama/mistral": {
		Provider:             "ollama",
		Model:                "mistral",
		InputPricePerMToken:  0.0,
		OutputPricePerMToken: 0.0,
		Currency:             "USD",
	},
	"cloudflare/llama-2-7b": {
		Provider:             "cloudflare",
		Model:                "llama-2-7b",
		InputPricePerMToken:  0.0,
		OutputPricePerMToken: 0.0,
		Currency:             "USD",
	},
	"cloudflare/mistral-7b": {
		Provider:             "cloudflare",
		Model:                "mistral-7b",
		InputPricePerMToken:  0.0,
		OutputPricePerMToken: 0.0,
		Currency:             "USD",
	},
	"moonshot/kimi-k2-0905-preview": {
		Provider:             "moonshot",
		Model:                "kimi-k2-0905-preview",
		InputPricePerMToken:  0.60,
		OutputPricePerMToken: 2.50,
		Currency:             "USD",
	},
	"moonshot/kimi-k2-0711-preview": {
		Provider:             "moonshot",
		Model:                "kimi-k2-0711-preview",
		InputPricePerMToken:  0.60,
		OutputPricePerMToken: 2.50,
		Currency:             "USD",
	},
	"moonshot/kimi-k2-turbo-preview": {
		Provider:             "moonshot",
		Model:                "kimi-k2-turbo-preview",
		InputPricePerMToken:  1.15,
		OutputPricePerMToken: 8.00,
		Currency:             "USD",
	},
	"moonshot/kimi-k2-thinking": {
		Provider:             "moonshot",
		Model:                "kimi-k2-thinking",
		InputPricePerMToken:  0.60,
		OutputPricePerMToken: 2.50,
		Currency:             "USD",
	},
	"moonshot/kimi-k2-thinking-turbo": {
		Provider:             "moonshot",
		Model:                "kimi-k2-thinking-turbo",
		InputPricePerMToken:  1.15,
		OutputPricePerMToken: 8.00,
		Currency:             "USD",
	},
	"moonshot/kimi-latest": {
		Provider:             "moonshot",
		Model:                "kimi-latest",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-8k": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-8k",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 2.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-32k": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-32k",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-128k": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-128k",
		InputPricePerMToken:  2.00,
		OutputPricePerMToken: 5.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-8k-vision-preview": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-8k-vision-preview",
		InputPricePerMToken:  0.20,
		OutputPricePerMToken: 2.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-32k-vision-preview": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-32k-vision-preview",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-128k-vision-preview": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-128k-vision-preview",
		InputPricePerMToken:  2.00,
		OutputPricePerMToken: 5.00,
		Currency:             "USD",
	},
	"moonshot/moonshot-v1-auto": {
		Provider:             "moonshot",
		Model:                "moonshot-v1-auto",
		InputPricePerMToken:  1.00,
		OutputPricePerMToken: 3.00,
		Currency:             "USD",
	},
}
