// Code generated by counterfeiter. DO NOT EDIT.
package agentdomain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/agent/domain"
)

type FakeCallApprover struct {
	RequiresApprovalStub        func(map[string]any, domain.AgentMode) bool
	requiresApprovalMutex       sync.RWMutex
	requiresApprovalArgsForCall []struct {
		arg1 map[string]any
		arg2 domain.AgentMode
	}
	requiresApprovalReturns struct {
		result1 bool
	}
	requiresApprovalReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCallApprover) RequiresApproval(arg1 map[string]any, arg2 domain.AgentMode) bool {
	fake.requiresApprovalMutex.Lock()
	ret, specificReturn := fake.requiresApprovalReturnsOnCall[len(fake.requiresApprovalArgsForCall)]
	fake.requiresApprovalArgsForCall = append(fake.requiresApprovalArgsForCall, struct {
		arg1 map[string]any
		arg2 domain.AgentMode
	}{arg1, arg2})
	stub := fake.RequiresApprovalStub
	fakeReturns := fake.requiresApprovalReturns
	fake.recordInvocation("RequiresApproval", []interface{}{arg1, arg2})
	fake.requiresApprovalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCallApprover) RequiresApprovalCallCount() int {
	fake.requiresApprovalMutex.RLock()
	defer fake.requiresApprovalMutex.RUnlock()
	return len(fake.requiresApprovalArgsForCall)
}

func (fake *FakeCallApprover) RequiresApprovalCalls(stub func(map[string]any, domain.AgentMode) bool) {
	fake.requiresApprovalMutex.Lock()
	defer fake.requiresApprovalMutex.Unlock()
	fake.RequiresApprovalStub = stub
}

func (fake *FakeCallApprover) RequiresApprovalArgsForCall(i int) (map[string]any, domain.AgentMode) {
	fake.requiresApprovalMutex.RLock()
	defer fake.requiresApprovalMutex.RUnlock()
	argsForCall := fake.requiresApprovalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCallApprover) RequiresApprovalReturns(result1 bool) {
	fake.requiresApprovalMutex.Lock()
	defer fake.requiresApprovalMutex.Unlock()
	fake.RequiresApprovalStub = nil
	fake.requiresApprovalReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeCallApprover) RequiresApprovalReturnsOnCall(i int, result1 bool) {
	fake.requiresApprovalMutex.Lock()
	defer fake.requiresApprovalMutex.Unlock()
	fake.RequiresApprovalStub = nil
	if fake.requiresApprovalReturnsOnCall == nil {
		fake.requiresApprovalReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.requiresApprovalReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeCallApprover) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCallApprover) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.CallApprover = new(FakeCallApprover)
