// Code generated by counterfeiter. DO NOT EDIT.
package agentdomain

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/agent/domain"
)

type FakeImageAnnotator struct {
	AnnotateImageStub        func(context.Context, domain.ImageAttachment, domain.AnnotateOptions) (*domain.ImageAnnotation, error)
	annotateImageMutex       sync.RWMutex
	annotateImageArgsForCall []struct {
		arg1 context.Context
		arg2 domain.ImageAttachment
		arg3 domain.AnnotateOptions
	}
	annotateImageReturns struct {
		result1 *domain.ImageAnnotation
		result2 error
	}
	annotateImageReturnsOnCall map[int]struct {
		result1 *domain.ImageAnnotation
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImageAnnotator) AnnotateImage(arg1 context.Context, arg2 domain.ImageAttachment, arg3 domain.AnnotateOptions) (*domain.ImageAnnotation, error) {
	fake.annotateImageMutex.Lock()
	ret, specificReturn := fake.annotateImageReturnsOnCall[len(fake.annotateImageArgsForCall)]
	fake.annotateImageArgsForCall = append(fake.annotateImageArgsForCall, struct {
		arg1 context.Context
		arg2 domain.ImageAttachment
		arg3 domain.AnnotateOptions
	}{arg1, arg2, arg3})
	stub := fake.AnnotateImageStub
	fakeReturns := fake.annotateImageReturns
	fake.recordInvocation("AnnotateImage", []interface{}{arg1, arg2, arg3})
	fake.annotateImageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImageAnnotator) AnnotateImageCallCount() int {
	fake.annotateImageMutex.RLock()
	defer fake.annotateImageMutex.RUnlock()
	return len(fake.annotateImageArgsForCall)
}

func (fake *FakeImageAnnotator) AnnotateImageCalls(stub func(context.Context, domain.ImageAttachment, domain.AnnotateOptions) (*domain.ImageAnnotation, error)) {
	fake.annotateImageMutex.Lock()
	defer fake.annotateImageMutex.Unlock()
	fake.AnnotateImageStub = stub
}

func (fake *FakeImageAnnotator) AnnotateImageArgsForCall(i int) (context.Context, domain.ImageAttachment, domain.AnnotateOptions) {
	fake.annotateImageMutex.RLock()
	defer fake.annotateImageMutex.RUnlock()
	argsForCall := fake.annotateImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeImageAnnotator) AnnotateImageReturns(result1 *domain.ImageAnnotation, result2 error) {
	fake.annotateImageMutex.Lock()
	defer fake.annotateImageMutex.Unlock()
	fake.AnnotateImageStub = nil
	fake.annotateImageReturns = struct {
		result1 *domain.ImageAnnotation
		result2 error
	}{result1, result2}
}

func (fake *FakeImageAnnotator) AnnotateImageReturnsOnCall(i int, result1 *domain.ImageAnnotation, result2 error) {
	fake.annotateImageMutex.Lock()
	defer fake.annotateImageMutex.Unlock()
	fake.AnnotateImageStub = nil
	if fake.annotateImageReturnsOnCall == nil {
		fake.annotateImageReturnsOnCall = make(map[int]struct {
			result1 *domain.ImageAnnotation
			result2 error
		})
	}
	fake.annotateImageReturnsOnCall[i] = struct {
		result1 *domain.ImageAnnotation
		result2 error
	}{result1, result2}
}

func (fake *FakeImageAnnotator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImageAnnotator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.ImageAnnotator = new(FakeImageAnnotator)
