// Code generated by counterfeiter. DO NOT EDIT.
package agentdomain

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/agent/domain"
)

type FakeSpeechService struct {
	SynthesizeStub        func(context.Context, string, string, string) error
	synthesizeMutex       sync.RWMutex
	synthesizeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	synthesizeReturns struct {
		result1 error
	}
	synthesizeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSpeechService) Synthesize(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.synthesizeMutex.Lock()
	ret, specificReturn := fake.synthesizeReturnsOnCall[len(fake.synthesizeArgsForCall)]
	fake.synthesizeArgsForCall = append(fake.synthesizeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.SynthesizeStub
	fakeReturns := fake.synthesizeReturns
	fake.recordInvocation("Synthesize", []interface{}{arg1, arg2, arg3, arg4})
	fake.synthesizeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpeechService) SynthesizeCallCount() int {
	fake.synthesizeMutex.RLock()
	defer fake.synthesizeMutex.RUnlock()
	return len(fake.synthesizeArgsForCall)
}

func (fake *FakeSpeechService) SynthesizeCalls(stub func(context.Context, string, string, string) error) {
	fake.synthesizeMutex.Lock()
	defer fake.synthesizeMutex.Unlock()
	fake.SynthesizeStub = stub
}

func (fake *FakeSpeechService) SynthesizeArgsForCall(i int) (context.Context, string, string, string) {
	fake.synthesizeMutex.RLock()
	defer fake.synthesizeMutex.RUnlock()
	argsForCall := fake.synthesizeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSpeechService) SynthesizeReturns(result1 error) {
	fake.synthesizeMutex.Lock()
	defer fake.synthesizeMutex.Unlock()
	fake.SynthesizeStub = nil
	fake.synthesizeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpeechService) SynthesizeReturnsOnCall(i int, result1 error) {
	fake.synthesizeMutex.Lock()
	defer fake.synthesizeMutex.Unlock()
	fake.SynthesizeStub = nil
	if fake.synthesizeReturnsOnCall == nil {
		fake.synthesizeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.synthesizeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpeechService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSpeechService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.SpeechService = new(FakeSpeechService)
