// Code generated by counterfeiter. DO NOT EDIT.
package agentdomain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/agent/domain"
)

type FakeSessionTool struct {
	NeedsSessionStub        func() bool
	needsSessionMutex       sync.RWMutex
	needsSessionArgsForCall []struct {
	}
	needsSessionReturns struct {
		result1 bool
	}
	needsSessionReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSessionTool) NeedsSession() bool {
	fake.needsSessionMutex.Lock()
	ret, specificReturn := fake.needsSessionReturnsOnCall[len(fake.needsSessionArgsForCall)]
	fake.needsSessionArgsForCall = append(fake.needsSessionArgsForCall, struct {
	}{})
	stub := fake.NeedsSessionStub
	fakeReturns := fake.needsSessionReturns
	fake.recordInvocation("NeedsSession", []interface{}{})
	fake.needsSessionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionTool) NeedsSessionCallCount() int {
	fake.needsSessionMutex.RLock()
	defer fake.needsSessionMutex.RUnlock()
	return len(fake.needsSessionArgsForCall)
}

func (fake *FakeSessionTool) NeedsSessionCalls(stub func() bool) {
	fake.needsSessionMutex.Lock()
	defer fake.needsSessionMutex.Unlock()
	fake.NeedsSessionStub = stub
}

func (fake *FakeSessionTool) NeedsSessionReturns(result1 bool) {
	fake.needsSessionMutex.Lock()
	defer fake.needsSessionMutex.Unlock()
	fake.NeedsSessionStub = nil
	fake.needsSessionReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeSessionTool) NeedsSessionReturnsOnCall(i int, result1 bool) {
	fake.needsSessionMutex.Lock()
	defer fake.needsSessionMutex.Unlock()
	fake.NeedsSessionStub = nil
	if fake.needsSessionReturnsOnCall == nil {
		fake.needsSessionReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.needsSessionReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeSessionTool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSessionTool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.SessionTool = new(FakeSessionTool)
