// Code generated by counterfeiter. DO NOT EDIT.
package agentdomain

import (
	"sync"

	"github.com/inference-gateway/cli/internal/agent/domain"
)

type FakeToolManifestLookup struct {
	ManifestStub        func(string) domain.ToolManifest
	manifestMutex       sync.RWMutex
	manifestArgsForCall []struct {
		arg1 string
	}
	manifestReturns struct {
		result1 domain.ToolManifest
	}
	manifestReturnsOnCall map[int]struct {
		result1 domain.ToolManifest
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeToolManifestLookup) Manifest(arg1 string) domain.ToolManifest {
	fake.manifestMutex.Lock()
	ret, specificReturn := fake.manifestReturnsOnCall[len(fake.manifestArgsForCall)]
	fake.manifestArgsForCall = append(fake.manifestArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ManifestStub
	fakeReturns := fake.manifestReturns
	fake.recordInvocation("Manifest", []interface{}{arg1})
	fake.manifestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeToolManifestLookup) ManifestCallCount() int {
	fake.manifestMutex.RLock()
	defer fake.manifestMutex.RUnlock()
	return len(fake.manifestArgsForCall)
}

func (fake *FakeToolManifestLookup) ManifestCalls(stub func(string) domain.ToolManifest) {
	fake.manifestMutex.Lock()
	defer fake.manifestMutex.Unlock()
	fake.ManifestStub = stub
}

func (fake *FakeToolManifestLookup) ManifestArgsForCall(i int) string {
	fake.manifestMutex.RLock()
	defer fake.manifestMutex.RUnlock()
	argsForCall := fake.manifestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeToolManifestLookup) ManifestReturns(result1 domain.ToolManifest) {
	fake.manifestMutex.Lock()
	defer fake.manifestMutex.Unlock()
	fake.ManifestStub = nil
	fake.manifestReturns = struct {
		result1 domain.ToolManifest
	}{result1}
}

func (fake *FakeToolManifestLookup) ManifestReturnsOnCall(i int, result1 domain.ToolManifest) {
	fake.manifestMutex.Lock()
	defer fake.manifestMutex.Unlock()
	fake.ManifestStub = nil
	if fake.manifestReturnsOnCall == nil {
		fake.manifestReturnsOnCall = make(map[int]struct {
			result1 domain.ToolManifest
		})
	}
	fake.manifestReturnsOnCall[i] = struct {
		result1 domain.ToolManifest
	}{result1}
}

func (fake *FakeToolManifestLookup) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeToolManifestLookup) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.ToolManifestLookup = new(FakeToolManifestLookup)
