// Code generated by counterfeiter. DO NOT EDIT.
package a2a

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/a2a/domain"
)

type FakeAgentCardService struct {
	GetAgentCardsStub        func(context.Context) ([]*domain.CachedAgentCard, error)
	getAgentCardsMutex       sync.RWMutex
	getAgentCardsArgsForCall []struct {
		arg1 context.Context
	}
	getAgentCardsReturns struct {
		result1 []*domain.CachedAgentCard
		result2 error
	}
	getAgentCardsReturnsOnCall map[int]struct {
		result1 []*domain.CachedAgentCard
		result2 error
	}
	GetConfiguredAgentsStub        func() []string
	getConfiguredAgentsMutex       sync.RWMutex
	getConfiguredAgentsArgsForCall []struct {
	}
	getConfiguredAgentsReturns struct {
		result1 []string
	}
	getConfiguredAgentsReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentCardService) GetAgentCards(arg1 context.Context) ([]*domain.CachedAgentCard, error) {
	fake.getAgentCardsMutex.Lock()
	ret, specificReturn := fake.getAgentCardsReturnsOnCall[len(fake.getAgentCardsArgsForCall)]
	fake.getAgentCardsArgsForCall = append(fake.getAgentCardsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetAgentCardsStub
	fakeReturns := fake.getAgentCardsReturns
	fake.recordInvocation("GetAgentCards", []interface{}{arg1})
	fake.getAgentCardsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentCardService) GetAgentCardsCallCount() int {
	fake.getAgentCardsMutex.RLock()
	defer fake.getAgentCardsMutex.RUnlock()
	return len(fake.getAgentCardsArgsForCall)
}

func (fake *FakeAgentCardService) GetAgentCardsCalls(stub func(context.Context) ([]*domain.CachedAgentCard, error)) {
	fake.getAgentCardsMutex.Lock()
	defer fake.getAgentCardsMutex.Unlock()
	fake.GetAgentCardsStub = stub
}

func (fake *FakeAgentCardService) GetAgentCardsArgsForCall(i int) context.Context {
	fake.getAgentCardsMutex.RLock()
	defer fake.getAgentCardsMutex.RUnlock()
	argsForCall := fake.getAgentCardsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentCardService) GetAgentCardsReturns(result1 []*domain.CachedAgentCard, result2 error) {
	fake.getAgentCardsMutex.Lock()
	defer fake.getAgentCardsMutex.Unlock()
	fake.GetAgentCardsStub = nil
	fake.getAgentCardsReturns = struct {
		result1 []*domain.CachedAgentCard
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentCardService) GetAgentCardsReturnsOnCall(i int, result1 []*domain.CachedAgentCard, result2 error) {
	fake.getAgentCardsMutex.Lock()
	defer fake.getAgentCardsMutex.Unlock()
	fake.GetAgentCardsStub = nil
	if fake.getAgentCardsReturnsOnCall == nil {
		fake.getAgentCardsReturnsOnCall = make(map[int]struct {
			result1 []*domain.CachedAgentCard
			result2 error
		})
	}
	fake.getAgentCardsReturnsOnCall[i] = struct {
		result1 []*domain.CachedAgentCard
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentCardService) GetConfiguredAgents() []string {
	fake.getConfiguredAgentsMutex.Lock()
	ret, specificReturn := fake.getConfiguredAgentsReturnsOnCall[len(fake.getConfiguredAgentsArgsForCall)]
	fake.getConfiguredAgentsArgsForCall = append(fake.getConfiguredAgentsArgsForCall, struct {
	}{})
	stub := fake.GetConfiguredAgentsStub
	fakeReturns := fake.getConfiguredAgentsReturns
	fake.recordInvocation("GetConfiguredAgents", []interface{}{})
	fake.getConfiguredAgentsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentCardService) GetConfiguredAgentsCallCount() int {
	fake.getConfiguredAgentsMutex.RLock()
	defer fake.getConfiguredAgentsMutex.RUnlock()
	return len(fake.getConfiguredAgentsArgsForCall)
}

func (fake *FakeAgentCardService) GetConfiguredAgentsCalls(stub func() []string) {
	fake.getConfiguredAgentsMutex.Lock()
	defer fake.getConfiguredAgentsMutex.Unlock()
	fake.GetConfiguredAgentsStub = stub
}

func (fake *FakeAgentCardService) GetConfiguredAgentsReturns(result1 []string) {
	fake.getConfiguredAgentsMutex.Lock()
	defer fake.getConfiguredAgentsMutex.Unlock()
	fake.GetConfiguredAgentsStub = nil
	fake.getConfiguredAgentsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeAgentCardService) GetConfiguredAgentsReturnsOnCall(i int, result1 []string) {
	fake.getConfiguredAgentsMutex.Lock()
	defer fake.getConfiguredAgentsMutex.Unlock()
	fake.GetConfiguredAgentsStub = nil
	if fake.getConfiguredAgentsReturnsOnCall == nil {
		fake.getConfiguredAgentsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getConfiguredAgentsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeAgentCardService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentCardService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.AgentCardService = new(FakeAgentCardService)
