// Code generated by counterfeiter. DO NOT EDIT.
package binaries

import (
	"context"
	"sync"

	"github.com/inference-gateway/cli/internal/binaries/domain"
)

type FakeStore struct {
	EnsureStub        func(context.Context, domain.Name) (string, error)
	ensureMutex       sync.RWMutex
	ensureArgsForCall []struct {
		arg1 context.Context
		arg2 domain.Name
	}
	ensureReturns struct {
		result1 string
		result2 error
	}
	ensureReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	InstallStub        func(context.Context, string, []domain.Name) error
	installMutex       sync.RWMutex
	installArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []domain.Name
	}
	installReturns struct {
		result1 error
	}
	installReturnsOnCall map[int]struct {
		result1 error
	}
	StatusStub        func(context.Context, []domain.Name) ([]domain.Status, error)
	statusMutex       sync.RWMutex
	statusArgsForCall []struct {
		arg1 context.Context
		arg2 []domain.Name
	}
	statusReturns struct {
		result1 []domain.Status
		result2 error
	}
	statusReturnsOnCall map[int]struct {
		result1 []domain.Status
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) Ensure(arg1 context.Context, arg2 domain.Name) (string, error) {
	fake.ensureMutex.Lock()
	ret, specificReturn := fake.ensureReturnsOnCall[len(fake.ensureArgsForCall)]
	fake.ensureArgsForCall = append(fake.ensureArgsForCall, struct {
		arg1 context.Context
		arg2 domain.Name
	}{arg1, arg2})
	stub := fake.EnsureStub
	fakeReturns := fake.ensureReturns
	fake.recordInvocation("Ensure", []interface{}{arg1, arg2})
	fake.ensureMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) EnsureCallCount() int {
	fake.ensureMutex.RLock()
	defer fake.ensureMutex.RUnlock()
	return len(fake.ensureArgsForCall)
}

func (fake *FakeStore) EnsureCalls(stub func(context.Context, domain.Name) (string, error)) {
	fake.ensureMutex.Lock()
	defer fake.ensureMutex.Unlock()
	fake.EnsureStub = stub
}

func (fake *FakeStore) EnsureArgsForCall(i int) (context.Context, domain.Name) {
	fake.ensureMutex.RLock()
	defer fake.ensureMutex.RUnlock()
	argsForCall := fake.ensureArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) EnsureReturns(result1 string, result2 error) {
	fake.ensureMutex.Lock()
	defer fake.ensureMutex.Unlock()
	fake.EnsureStub = nil
	fake.ensureReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) EnsureReturnsOnCall(i int, result1 string, result2 error) {
	fake.ensureMutex.Lock()
	defer fake.ensureMutex.Unlock()
	fake.EnsureStub = nil
	if fake.ensureReturnsOnCall == nil {
		fake.ensureReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.ensureReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Install(arg1 context.Context, arg2 string, arg3 []domain.Name) error {
	var arg3Copy []domain.Name
	if arg3 != nil {
		arg3Copy = make([]domain.Name, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.installMutex.Lock()
	ret, specificReturn := fake.installReturnsOnCall[len(fake.installArgsForCall)]
	fake.installArgsForCall = append(fake.installArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []domain.Name
	}{arg1, arg2, arg3Copy})
	stub := fake.InstallStub
	fakeReturns := fake.installReturns
	fake.recordInvocation("Install", []interface{}{arg1, arg2, arg3Copy})
	fake.installMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) InstallCallCount() int {
	fake.installMutex.RLock()
	defer fake.installMutex.RUnlock()
	return len(fake.installArgsForCall)
}

func (fake *FakeStore) InstallCalls(stub func(context.Context, string, []domain.Name) error) {
	fake.installMutex.Lock()
	defer fake.installMutex.Unlock()
	fake.InstallStub = stub
}

func (fake *FakeStore) InstallArgsForCall(i int) (context.Context, string, []domain.Name) {
	fake.installMutex.RLock()
	defer fake.installMutex.RUnlock()
	argsForCall := fake.installArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStore) InstallReturns(result1 error) {
	fake.installMutex.Lock()
	defer fake.installMutex.Unlock()
	fake.InstallStub = nil
	fake.installReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) InstallReturnsOnCall(i int, result1 error) {
	fake.installMutex.Lock()
	defer fake.installMutex.Unlock()
	fake.InstallStub = nil
	if fake.installReturnsOnCall == nil {
		fake.installReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.installReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) Status(arg1 context.Context, arg2 []domain.Name) ([]domain.Status, error) {
	var arg2Copy []domain.Name
	if arg2 != nil {
		arg2Copy = make([]domain.Name, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.statusMutex.Lock()
	ret, specificReturn := fake.statusReturnsOnCall[len(fake.statusArgsForCall)]
	fake.statusArgsForCall = append(fake.statusArgsForCall, struct {
		arg1 context.Context
		arg2 []domain.Name
	}{arg1, arg2Copy})
	stub := fake.StatusStub
	fakeReturns := fake.statusReturns
	fake.recordInvocation("Status", []interface{}{arg1, arg2Copy})
	fake.statusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) StatusCallCount() int {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	return len(fake.statusArgsForCall)
}

func (fake *FakeStore) StatusCalls(stub func(context.Context, []domain.Name) ([]domain.Status, error)) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = stub
}

func (fake *FakeStore) StatusArgsForCall(i int) (context.Context, []domain.Name) {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	argsForCall := fake.statusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) StatusReturns(result1 []domain.Status, result2 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	fake.statusReturns = struct {
		result1 []domain.Status
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) StatusReturnsOnCall(i int, result1 []domain.Status, result2 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	if fake.statusReturnsOnCall == nil {
		fake.statusReturnsOnCall = make(map[int]struct {
			result1 []domain.Status
			result2 error
		})
	}
	fake.statusReturnsOnCall[i] = struct {
		result1 []domain.Status
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.Store = new(FakeStore)
