gateway:
  url: http://localhost:8080
  api_key: ""
  timeout: 200
logging:
  debug: false
tools:
  enabled: true
  sandbox:
    directories:
      - .
      - /tmp
    protected_paths:
      - .infer/
      - .git/
      - '*.env'
  bash:
    enabled: true
    whitelist:
      commands:
        - ls
        - pwd
        - echo
        - wc
        - sort
        - uniq
        - gh
        - task
      patterns:
        - ^git status$
        - ^git log --oneline -n [0-9]+$
        - ^docker ps$
        - ^kubectl get pods$
  read:
    enabled: true
    require_approval: false
  write:
    enabled: true
    require_approval: true
  edit:
    enabled: true
    require_approval: true
  delete:
    enabled: true
    require_approval: true
  grep:
    enabled: true
    backend: auto
    require_approval: false
  tree:
    enabled: true
    require_approval: false
  web_fetch:
    enabled: true
    whitelisted_domains:
      - github.com
      - golang.org
    github:
      enabled: true
      token: ""
      base_url: https://api.github.com
    safety:
      max_size: 8192
      timeout: 30
      allow_redirect: true
    cache:
      enabled: true
      ttl: 3600
      max_size: 52428800
  web_search:
    enabled: true
    default_engine: duckduckgo
    max_results: 10
    engines:
      - duckduckgo
      - google
    timeout: 10
  todo_write:
    enabled: true
    require_approval: false
  safety:
    require_approval: true
compact:
  output_dir: .infer
  summary_model: ""
chat:
  default_model: ""
  system_prompt: |-
    Software engineering assistant. Concise (<4 lines), direct answers only.

    RULES:
    - Security: Defensive only (analysis, detection, docs)
    - Style: No preamble/postamble, no emojis/comments unless asked
    - Code: Follow existing patterns, check deps, no secrets
    - Tasks: Use TodoWrite, mark progress immediately
    - Chat exports: Read only "## Summary" to "---" section
    - Tools: Batch calls, prefer Grep for search
    - Workflow: Plan→Search→Implement→Test(task test)→Lint→Commit(if asked)
  optimization:
    enabled: false
    max_history: 10
    compact_threshold: 20
    truncate_large_outputs: true
    skip_redundant_confirmations: true
