gateway:
  url: http://localhost:8080
  api_key: ""
  timeout: 30
output:
  format: text
  quiet: false
  debug: false
tools:
  enabled: true
  bash:
    enabled: true
    whitelist:
      commands:
        - ls
        - pwd
        - echo
        - grep
        - wc
        - sort
        - uniq
      patterns:
        - ^git status$
        - ^git log --oneline -n [0-9]+$
        - ^docker ps$
        - ^kubectl get pods$
  read:
    enabled: true
    require_approval: false
  file_search:
    enabled: true
    require_approval: false
  tree:
    enabled: true
    require_approval: false
  fetch:
    enabled: true
    whitelisted_domains:
      - github.com
      - golang.org
    github:
      enabled: true
      token: ""
      base_url: https://api.github.com
    safety:
      max_size: 8192
      timeout: 30
      allow_redirect: true
    cache:
      enabled: true
      ttl: 3600
      max_size: 52428800
  web_search:
    enabled: true
    default_engine: duckduckgo
    max_results: 10
    engines:
      - duckduckgo
      - google
    timeout: 10
  write_todos:
    enabled: true
    require_approval: false
  safety:
    require_approval: true
  exclude_paths:
    - .infer/
    - .infer/*
compact:
  output_dir: .infer
chat:
  default_model: ""
  system_prompt: ""
