// Code generated by counterfeiter. DO NOT EDIT.
package scheduler

import (
	"context"
	"sync"

	domaina "github.com/inference-gateway/cli/internal/agent/domain"
	"github.com/inference-gateway/cli/internal/scheduler/domain"
)

type FakeJobIdleReporter struct {
	CloseStub        func()
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	IdleStub        func() bool
	idleMutex       sync.RWMutex
	idleArgsForCall []struct {
	}
	idleReturns struct {
		result1 bool
	}
	idleReturnsOnCall map[int]struct {
		result1 bool
	}
	MetaStub        func() domain.JobMeta
	metaMutex       sync.RWMutex
	metaArgsForCall []struct {
	}
	metaReturns struct {
		result1 domain.JobMeta
	}
	metaReturnsOnCall map[int]struct {
		result1 domain.JobMeta
	}
	RunStub        func(context.Context, func(domain.JobSignal)) domaina.ToolExecutionResult
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
		arg2 func(domain.JobSignal)
	}
	runReturns struct {
		result1 domaina.ToolExecutionResult
	}
	runReturnsOnCall map[int]struct {
		result1 domaina.ToolExecutionResult
	}
	WindStub        func(context.Context, domain.WindSignal) error
	windMutex       sync.RWMutex
	windArgsForCall []struct {
		arg1 context.Context
		arg2 domain.WindSignal
	}
	windReturns struct {
		result1 error
	}
	windReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobIdleReporter) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeJobIdleReporter) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeJobIdleReporter) CloseCalls(stub func()) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeJobIdleReporter) Idle() bool {
	fake.idleMutex.Lock()
	ret, specificReturn := fake.idleReturnsOnCall[len(fake.idleArgsForCall)]
	fake.idleArgsForCall = append(fake.idleArgsForCall, struct {
	}{})
	stub := fake.IdleStub
	fakeReturns := fake.idleReturns
	fake.recordInvocation("Idle", []interface{}{})
	fake.idleMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobIdleReporter) IdleCallCount() int {
	fake.idleMutex.RLock()
	defer fake.idleMutex.RUnlock()
	return len(fake.idleArgsForCall)
}

func (fake *FakeJobIdleReporter) IdleCalls(stub func() bool) {
	fake.idleMutex.Lock()
	defer fake.idleMutex.Unlock()
	fake.IdleStub = stub
}

func (fake *FakeJobIdleReporter) IdleReturns(result1 bool) {
	fake.idleMutex.Lock()
	defer fake.idleMutex.Unlock()
	fake.IdleStub = nil
	fake.idleReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeJobIdleReporter) IdleReturnsOnCall(i int, result1 bool) {
	fake.idleMutex.Lock()
	defer fake.idleMutex.Unlock()
	fake.IdleStub = nil
	if fake.idleReturnsOnCall == nil {
		fake.idleReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.idleReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeJobIdleReporter) Meta() domain.JobMeta {
	fake.metaMutex.Lock()
	ret, specificReturn := fake.metaReturnsOnCall[len(fake.metaArgsForCall)]
	fake.metaArgsForCall = append(fake.metaArgsForCall, struct {
	}{})
	stub := fake.MetaStub
	fakeReturns := fake.metaReturns
	fake.recordInvocation("Meta", []interface{}{})
	fake.metaMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobIdleReporter) MetaCallCount() int {
	fake.metaMutex.RLock()
	defer fake.metaMutex.RUnlock()
	return len(fake.metaArgsForCall)
}

func (fake *FakeJobIdleReporter) MetaCalls(stub func() domain.JobMeta) {
	fake.metaMutex.Lock()
	defer fake.metaMutex.Unlock()
	fake.MetaStub = stub
}

func (fake *FakeJobIdleReporter) MetaReturns(result1 domain.JobMeta) {
	fake.metaMutex.Lock()
	defer fake.metaMutex.Unlock()
	fake.MetaStub = nil
	fake.metaReturns = struct {
		result1 domain.JobMeta
	}{result1}
}

func (fake *FakeJobIdleReporter) MetaReturnsOnCall(i int, result1 domain.JobMeta) {
	fake.metaMutex.Lock()
	defer fake.metaMutex.Unlock()
	fake.MetaStub = nil
	if fake.metaReturnsOnCall == nil {
		fake.metaReturnsOnCall = make(map[int]struct {
			result1 domain.JobMeta
		})
	}
	fake.metaReturnsOnCall[i] = struct {
		result1 domain.JobMeta
	}{result1}
}

func (fake *FakeJobIdleReporter) Run(arg1 context.Context, arg2 func(domain.JobSignal)) domaina.ToolExecutionResult {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
		arg2 func(domain.JobSignal)
	}{arg1, arg2})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1, arg2})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobIdleReporter) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeJobIdleReporter) RunCalls(stub func(context.Context, func(domain.JobSignal)) domaina.ToolExecutionResult) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeJobIdleReporter) RunArgsForCall(i int) (context.Context, func(domain.JobSignal)) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobIdleReporter) RunReturns(result1 domaina.ToolExecutionResult) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 domaina.ToolExecutionResult
	}{result1}
}

func (fake *FakeJobIdleReporter) RunReturnsOnCall(i int, result1 domaina.ToolExecutionResult) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 domaina.ToolExecutionResult
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 domaina.ToolExecutionResult
	}{result1}
}

func (fake *FakeJobIdleReporter) Wind(arg1 context.Context, arg2 domain.WindSignal) error {
	fake.windMutex.Lock()
	ret, specificReturn := fake.windReturnsOnCall[len(fake.windArgsForCall)]
	fake.windArgsForCall = append(fake.windArgsForCall, struct {
		arg1 context.Context
		arg2 domain.WindSignal
	}{arg1, arg2})
	stub := fake.WindStub
	fakeReturns := fake.windReturns
	fake.recordInvocation("Wind", []interface{}{arg1, arg2})
	fake.windMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeJobIdleReporter) WindCallCount() int {
	fake.windMutex.RLock()
	defer fake.windMutex.RUnlock()
	return len(fake.windArgsForCall)
}

func (fake *FakeJobIdleReporter) WindCalls(stub func(context.Context, domain.WindSignal) error) {
	fake.windMutex.Lock()
	defer fake.windMutex.Unlock()
	fake.WindStub = stub
}

func (fake *FakeJobIdleReporter) WindArgsForCall(i int) (context.Context, domain.WindSignal) {
	fake.windMutex.RLock()
	defer fake.windMutex.RUnlock()
	argsForCall := fake.windArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeJobIdleReporter) WindReturns(result1 error) {
	fake.windMutex.Lock()
	defer fake.windMutex.Unlock()
	fake.WindStub = nil
	fake.windReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobIdleReporter) WindReturnsOnCall(i int, result1 error) {
	fake.windMutex.Lock()
	defer fake.windMutex.Unlock()
	fake.WindStub = nil
	if fake.windReturnsOnCall == nil {
		fake.windReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.windReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeJobIdleReporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJobIdleReporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.JobIdleReporter = new(FakeJobIdleReporter)
